# Feature selection and feature engineering

Based on paper in folder `/data/`.

In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression

pd.set_option("display.max_columns", 200)
pd.set_option("display.max_colwidth", 200)
%matplotlib inline

# Reading in our data

## Every single person in a crash

We'll start by reading in the list of people who were involved in an accident.

**Call this dataframe `people`.**

In [2]:
people = pd.read_csv('combined-person-data.csv')
people

/Users/lindseyfeingold/.pyenv/versions/3.7.1/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3049: DtypeWarning: Columns (5,15,26) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,AIRBAG_DEPLOYED,ALCOHOL_TESTTYPE_CODE,ALCOHOL_TEST_CODE,BAC_CODE,CDL_FLAG,CLASS,CONDITION_CODE,DATE_OF_BIRTH,DRUG_TESTRESULT_CODE,DRUG_TEST_CODE,EJECT_CODE,EMS_UNIT_LABEL,EQUIP_PROB_CODE,FAULT_FLAG,INJ_SEVER_CODE,LICENSE_STATE_CODE,MOVEMENT_CODE,OCC_SEAT_POS_CODE,PED_LOCATION_CODE,PED_OBEY_CODE,PED_TYPE_CODE,PED_VISIBLE_CODE,PERSON_ID,PERSON_TYPE,REPORT_NO,SAF_EQUIP_CODE,SEX_CODE,VEHICLE_ID
0,1.0,NaN,0.0,NaN,N,C,0.0,1952-04-20 00:00:00,NaN,0.0,1.0,NaN,1.0,N,1,PA,NaN,NaN,NaN,NaN,NaN,NaN,48dd00ee-e033-47e7-ad1e-0b734020301b,D,AB4284000S,13.0,F,eb6aadb8-dacb-4744-a1a7-ab812c96f27f
1,1.0,NaN,0.0,NaN,N,NaN,0.0,1985-05-28 00:00:00,NaN,0.0,0.0,NaN,0.0,N,1,MD,NaN,NaN,NaN,NaN,NaN,NaN,166296bd-ffd3-4c16-aa74-4f4bf4139d8d,D,AB4313000X,13.0,F,b463eb20-2f01-4200-9d6f-b18888ce2593
2,1.0,NaN,0.0,NaN,N,C,0.0,1960-10-04 00:00:00,NaN,0.0,0.0,NaN,0.0,Y,1,MD,NaN,NaN,NaN,NaN,NaN,NaN,f3b2743f-fbc3-4345-9419-56a0ca29102c,D,AB4313000X,13.0,F,3c8629d0-d524-47c1-bfbc-b18e07f3087e
3,1.0,NaN,0.0,NaN,N,B,0.0,1971-05-28 00:00:00,NaN,0.0,1.0,NaN,0.0,N,1,MD,NaN,NaN,NaN,NaN,NaN,NaN,5bbe589b-a2db-4dbb-be9b-17a800d69a08,D,AB4313000Y,0.0,F,c4628cdb-f295-4a24-8a4b-653741ac6ae7
4,1.0,NaN,0.0,NaN,N,D,0.0,1955-04-23 00:00:00,NaN,0.0,0.0,NaN,1.0,N,1,SC,NaN,NaN,NaN,NaN,NaN,NaN,b914136f-5ecd-46bb-94ec-ff5d4136c3eb,D,AB4669001F,13.0,F,cdda1580-fd79-4358-8819-c2250f494591
5,1.0,NaN,0.0,NaN,N,C,0.0,1957-02-23 00:00:00,NaN,0.0,0.0,NaN,1.0,Y,1,MD,NaN,NaN,NaN,NaN,NaN,NaN,9d749007-0354-4d82-809e-8a3de66d6167,D,AB49430024,13.0,F,d4213216-3c25-4097-b510-8f0bfc39a1bc
6,1.0,NaN,0.0,NaN,N,C,0.0,1990-11-05 00:00:00,NaN,0.0,1.0,NaN,1.0,N,1,MD,NaN,NaN,NaN,NaN,NaN,NaN,21fff0f9-ed13-4b87-ac04-29d018aff9d4,D,AB5218001Y,13.0,F,4dea42c3-e02c-4c6b-8ea0-c2f8c17f147f
7,1.0,NaN,0.0,NaN,N,NaN,0.0,1954-01-25 00:00:00,NaN,0.0,1.0,NaN,0.0,N,1,MD,NaN,NaN,NaN,NaN,NaN,NaN,34b771f8-40c6-410c-a8d7-9640261204fa,D,AB6133000N,0.0,F,f2888089-5fc9-44dd-ad50-8ab446cdf247
8,1.0,NaN,0.0,NaN,N,C,0.0,1969-06-18 00:00:00,NaN,0.0,1.0,NaN,0.0,N,1,MD,NaN,NaN,NaN,NaN,NaN,NaN,e4b74c8d-ec2c-438d-b768-aae7a0435eb4,D,AB64220007,13.0,F,5464f341-7ce6-4692-b0f1-3fdb3339753f
9,1.0,NaN,0.0,NaN,N,NaN,0.0,1981-02-18 00:00:00,NaN,0.0,1.0,NaN,0.0,Y,1,MD,NaN,NaN,NaN,NaN,NaN,NaN,ba99fc8c-8a87-47f9-9e4b-a99c664d8494,D,AC12390045,99.0,F,5445db7e-a933-43c7-bef6-18f91396c111
10,1.0,NaN,0.0,NaN,N,CM,0.0,1965-05-31 00:00:00,NaN,0.0,1.0,NaN,1.0,N,1,MD,NaN,NaN,NaN,NaN,NaN,NaN,2b259804-38c1-4617-a81b-8067cced311b,D,AC12880051,13.0,F,ed1cca0d-bbdd-4340-8483-65d135340e2b
11,1.0,NaN,0.0,NaN,N,C,0.0,1979-06-27 00:00:00,NaN,0.0,1.0,NaN,1.0,N,1,MD,NaN,NaN,NaN,NaN,NaN,NaN,e6796c69-7af5-4dc8-a0c8-90993551dbd2,D,AC12880051,13.0,F,67c42997-dbeb-4164-9bb7-2eb007b170bd
12,0.0,NaN,0.0,NaN,N,C,0.0,1982-10-14 00:00:00,NaN,0.0,1.0,NaN,1.0,N,1,MD,NaN,NaN,NaN,NaN,NaN,NaN,c1454625-8550-4452-801e-27a16b744d16,D,AC12880052,13.0,F,a6cd46d4-51be-4694-abe7-7beef45ee38d
13,1.0,NaN,0.0,NaN,N,C,0.0,1977-07-12 00:00:00,NaN,0.0,1.0,NaN,1.0,N,1,GA,NaN,NaN,NaN,NaN,NaN,NaN,e7b9a37b-21a0-4025-9183-988ff5b76039,D,AC12880059,13.0,F,ebb5b203-93ca-48da-91fb-9f3656aca2b6
14,1.0,NaN,0.0,NaN,N,C,0.0,1978-01-15 00:00:00,NaN,0.0,1.0,NaN,1.0,N,1,MD,NaN,NaN,NaN,NaN,NaN,NaN,be98aa54-dc83-4889-8a92-544787cb3bb8,D,AC1513000L,13.0,F,dd05dc96-d655-4001-98a5-330b4af29fc6
15,1.0,NaN,0.0,NaN,N,C,0.0,1968-01-23 00:00:00,NaN,0.0,0.0,NaN,1.0,N,1,MD,NaN,NaN,NaN,NaN,NaN,NaN,0c216b0d-3d61-44f3-9e46-e84cc1b46ea8,D,AC1679002R,13.0,F,b0664a42-f64c-4721-96c8-95299ec8537d
16,3.0,NaN,0.0,NaN,N,C,0.0,1997-08-04 00:00:00,NaN,0.0,1.0,NaN,1.0,N,1,MD,NaN,NaN,NaN,NaN,NaN,NaN,5f88ab1b-3488-42e7-8141-02a0691904f8,D,AC17270049,13.0,F,41aaaf50-ccc8-4c95-a96f-d4ef9dd7611a
17,1.0,NaN,0.0,NaN,N,C,0.0,2001-10-07 00:00:00,NaN,0.0,1.0,NaN,1.0,Y,1,MD,NaN,NaN,NaN,NaN,NaN,NaN,91a2cc43-8b84-4f33-a62d-a45f7918b2c4,D,AC1727004D,13.0,F,ef1e5466-7e3d-4762-9ef7-f3a8f2458408
18,1.0,NaN,0.0,NaN,N,CM,0.0,1959-08-12 00:00:00,NaN,0.0,1.0,NaN,1.0,N,1,MD,NaN,NaN,NaN,NaN,NaN,NaN,f6ce1250-6da6-40cb-8580-cdd9328807f3,D,AC1866008M,13.0,F,d584d9cf-941d-4ae6-831f-0a5265e75e34
19,1.0,NaN,0.0,NaN,N,C,0.0,1995-10-12 00:00:00,NaN,0.0,0.0,NaN,1.0,N,1,MD,NaN,NaN,NaN,NaN,NaN,NaN,d0b616d2-3707-40da-a20e-aad4ce04d0dd,D,AC19490050,13.0,F,40036852-8c98-4c35-8e4d-9f8ee398280d
20,1.0,NaN,0.0,NaN,N,C,0.0,1957-03-14 00:00:00,NaN,0.0,1.0,NaN,1.0,N,1,MD,NaN,NaN,NaN,NaN,NaN,NaN,20900c11-032a-45e8-84eb-0452a0f7749f,D,AC1964004T,13.0,F,23bcfda9-5793-44bf-a06b-418de814d104
21,1.0,NaN,0.0,NaN,N,C,0.0,1988-11-29 00:00:00,NaN,0.0,1.0,NaN,1.0,N,1,MD,NaN,NaN,NaN,NaN,NaN,NaN,9fb2ce57-5810-40ba-9a43-80a7592cce6c,D,AC1964004Y,13.0,F,7a14d7c2-c90f-424e-a48e-82deb5898c00
22,1.0,NaN,0.0,NaN,N,CM,0.0,1980-08-06 00:00:00,NaN,0.0,1.0,NaN,1.0,N,1,MD,NaN,NaN,NaN,NaN,NaN,NaN,117eea3f-e1b6-49e3-85cd-ee2f08fc8064,D,AC19640058,13.0,F,eed7f5a8-c225-4055-94db-ca3819f40c13
23,1.0,NaN,0.0,NaN,N,D,0.0,1988-01-19 00:00:00,NaN,0.0,1.0,NaN,1.0,Y,1,DE,NaN,NaN,NaN,NaN,NaN,NaN,a2c4042a-bbe0-4e1e-93ef-b91e99cf3585,D,AC19640058,13.0,F,9a76d26f-e6f2-44b6-a3f7-d58ca6e5b395
24,1.0,NaN,0.0,NaN,N,C,0.0,1963-09-12 00:00:00,NaN,0.0,0.0,NaN,0.0,N,1,MD,NaN,NaN,NaN,NaN,NaN,NaN,eda4afc0-57d3-474b-9705-0c35324930b1,D,AC2001004T,13.0,F,2425c075-8ec7-45e4-950b-012bf7c46a61
25,99.0,NaN,0.0,NaN,N,C,0.0,1967-01-25 00:00:00,NaN,0.0,0.0,NaN,99.0,Y,1,MD,NaN,NaN,NaN,NaN,NaN,NaN,cc54b296-770b-47a9-906b-1a242086090a,D,AC2001004T,99.0,F,85b7eb4c-93e7-4aa0-87e4-b451d4693692
26,0.0,NaN,0.0,NaN,N,C,0.0,1951-08-01 00:00:00,NaN,0.0,0.0,NaN,0.0,N,1,MD,NaN,NaN,NaN,NaN,NaN,NaN,fc485a26-e352-40a0-ab2c-a10fa183210f,D,AC2001005B,13.0,F,29c01834-fde1-4ce3-8c8e-ae3aa977b313
27,0.0,NaN,0.0,NaN,N,C,0.0,1972-09-24 00:00:00,NaN,0.0,0.0,NaN,0.0,N,1,MD,NaN,NaN,NaN,NaN,NaN,NaN,be8f8eba-1b44-48a5-84c7-76d57c52c7fa,D,AC2001005C,13.0,F,4d7c4fa4-36b7-4698-9c92-c495171104e6
28,1.0,NaN,0.0,NaN,N,C,0.0,1992-10-22 00:00:00,NaN,0.0,1.0,NaN,1.0,N,1,MD,NaN,NaN,NaN,NaN,NaN,NaN,c9a8c733-ec55-417c-9e22-4559ede47e68,D,AC2030005Q,13.0,F,e57b7d9a-4984-4ace-9c4c-f6716b131f28
29,1.0,NaN,0.0,NaN,N,C,0.0,1988-11-27 00:00:00,NaN,0.0,1.0,NaN,1.0,N,1,MD,NaN,NaN,NaN,NaN,NaN,NaN,65c48579-3d2f-4ab0-a790-2d9843014f1a,D,AC2045003X,13.0,F,f299a853-1488-4af0-ab4c-e1a1aaf4c07d
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
888253,99.0,NaN,0.0,NaN,N,NaN,99.0,NaN,NaN,0.0,1.0,NaN,99.0,Y,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6dc60fa9-b20b-47cf-89a3-d750bce67a90,D,ADX007004C,99.0,NaN,7822a4a9-6856-4b34-a9d5-4d1e54e5a777
888254,1.0,NaN,0.0,NaN,N,NaN,99.0,NaN,NaN,0.0,1.0,NaN,99.0,Y,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,c11c460a-05f5-4e01-96c7-52692ecd0ebd,D,AE50320010,99.0,NaN,d56aea25-12cc-4bba-8915-ba97349aeaa4
888255,99.0,NaN,0.0,NaN,N,NaN,99.0,NaN,NaN,0.0,99.0,NaN,99.0,Y,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,d240380c-a4b2-46e8-bb1d-666a6ac2081c,D,AE5315001N,99.0,NaN,76b7a0be-e00e-48a1-932c-1fafe1230b5b
888256,99.0,NaN,0.0,NaN,N,NaN,99.0,NaN,NaN,0.0,99.0,NaN,99.0,Y,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14170b54-fe96-463d-aa82-79d23138bd8d,D,DA31330011,99.0,NaN,05219a96-2d6e-419b-bc21-179136635051
888257,0.0,NaN,99.0,NaN,N,NaN,99.0,NaN,NaN,99.0,0.0,NaN,99.0,Y,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,91e8e783-9667-4f9e-baa0-9ef3c9610d5e,D,DA37170018,99.0,NaN,a99c3c64-a16c-44ee-ae4d-512aa5f55fd0
888258,1.0,NaN,0.0,NaN,N,NaN,99.0,NaN,NaN,0.0,1.0,NaN,99.0,Y,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2808714b-c6bc-4da0-a6ca-68f27ecaafad,D,DA39670017,99.0,NaN,20b661c9-b377-45e7-8502-7c53ca7e879b
888259,99.0,NaN,0.0,NaN,N,NaN,99.0,NaN,NaN,0.0,0.0,NaN,99.0,Y,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,84b3a562-be7c-443c-b1d1-d2d264a5aa63,D,DA4029000W,99.0,NaN,f0277ea9-de39-4d80-9e3a-dd4ee4fef138
888260,0.0,NaN,0.0,NaN,N,NaN,99.0,NaN,NaN,0.0,1.0,NaN,99.0,Y,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,53d05b8a-9b21-4aa6-a43e-2b3fe9b05f32,D,MDTA10350007,99.0,NaN,a567fba7-838e-40eb-96cc-433661832271
888261,99.0,NaN,0.0,NaN,N,NaN,99.0,NaN,NaN,0.0,1.0,NaN,1.0,Y,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3839de05-68cf-48bb-b4f2-f424cd5a348b,D,MDTA16500012,13.0,NaN,e6ac43cd-fcf8-4409-a3d1-d082e7f5ed7f
888262,2.0,NaN,0.0,NaN,N,NaN,99.0,NaN,NaN,0.0,1.0,NaN,1.0,Y,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14f23934-a8ac-4e12-8e55-9c0bf281c5be,D,MSP57580036,13.0,NaN,62952733-1ecf-4f3d-b526-3f63cd018ab6
888263,2.0,NaN,0.0,NaN,N,NaN,99.0,NaN,NaN,0.0,1.0,NaN,1.0,Y,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,a05b5aca-424d-491c-bfa5-9bd6a29948bf,D,MSP57580036,99.0,NaN,bfac7b5e-8528-4099-b9ac-fecfbd18905a
888264,1.0,NaN,99.0,NaN,N,NaN,99.0,NaN,NaN,99.0,1.0,NaN,1.0,N,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,b3b20365-059b-4195-93aa-10ccde4f0933,D,MSP622500BR,13.0,NaN,cab8d3a3-34af-46d3-819d-bca55011e577
888265,1.0,NaN,99.0,NaN,N,NaN,99.0,NaN,NaN,99.0,1.0,NaN,1.0,N,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,fe873e0e-d5bb-4fe6-81b1-8624beea989b,D,MSP622500BS,13.0,NaN,4e8f5ceb-591e-438c-b190-08c87b195f47
888266,0.0,NaN,0.0,NaN,N,NaN,99.0,NaN,NaN,0.0,1.0,NaN,99.0,Y,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1b69232f-f5b0-4a0a-b315-8e05a87d94f6,D,MSP67290009,99.0,NaN,5c1e3d20-08dd-4fa1-b7e8-cd00fb82f4c0
888267,0.0,NaN,0.0,NaN,N,NaN,99.0,NaN,NaN,0.0,1.0,NaN,99.0,Y,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2ba326f5-56d2-4071-a950-845bd962a3ec,D,MSP6729000G,99.0,NaN,673b186d-c1f2-44ed-88f9-13a853b481aa
888268,2.0,NaN,0.0,NaN,N,NaN,99.0,NaN,NaN,0.0,1.0,NaN,99.0,Y,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,09f73388-f604-40a4-9898-4ee157b95f58,D,MSP6729000H,99.0,NaN,62a74a15-6bf5-417a-a2da-202f127dca03
888269,1.0,NaN,0.0,NaN,N,NaN,99.0,NaN,NaN,0.0,1.0,NaN,0.0,Y,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18f1a2e8-cbf2-4ce3-8d00-46c8d89aaf3f,D,MTA0352000G,99.0,NaN,dcaf6752-9cd3-46f0-adae-68bc8f54df5f
888270,4.0,NaN,0.0,NaN,N,NaN,99.0,NaN,NaN,0.0,0.0,NaN,1.0,Y,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2a16cf56-2e31-4c92-9487-f55739870293,D,ZD3111002K,13.0,NaN,de2bad99-b9b2-44cd-ad70-8159540e23b1
888271,2.0,NaN,99.0,NaN,N,NaN,99.0,NaN,NaN,99.0,1.0,NaN,99.0,Y,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,80ed5a4e-cc54-4c86-946a-a0eaa6dea544,D,ZG0936000L,99.0,NaN,d3918ed9-6c21-4ab3-965a-2382295ba9a9
888272,2.0,NaN,99.0,NaN,N,NaN,99.0,NaN,NaN,99.0,99.0,NaN,0.0,Y,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,819a1b83-2c1e-4a09-b9b2-dd005da08c59,D,ZH0541002F,1.0,NaN,bdb71267-5eda-485c-b347-57ef1ed691c8
888273,99.0,NaN,0.0,NaN,N,NaN,99.0,NaN,NaN,0.0,99.0,NaN,99.0,Y,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,113aeed7-7e77-456c-a021-ebe639de52c1,D,ADH8240016,99.0,NaN,4a407c83-07e4-412b-b297-38baea98e003
888274,99.0,NaN,0.0,NaN,N,NaN,99.0,NaN,NaN,0.0,1.0,NaN,99.0,Y,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,eece8134-23fb-494b-9780-e955993144df,D,ADI865001B,99.0,NaN,661687a1-4d34-4a95-a70d-fd281320ee11
888275,99.0,NaN,0.0,NaN,N,NaN,99.0,NaN,NaN,0.0,99.0,NaN,99.0,Y,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ec37c566-43b9-413b-9bb5-381c90077e9a,D,BJ01860009,99.0,NaN,09ac11a0-2f18-4007-97c0-52e650d654ea
888276,0.0,NaN,0.0,NaN,N,NaN,99.0,NaN,NaN,0.0,99.0,NaN,99.0,Y,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,d493d31e-aef3-4027-b43a-c4bbf6e093f7,D,BJ0186000G,99.0,NaN,1876b666-0cf1-4a8c-8ba7-b4fa75995e19
888277,99.0,99.0,0.0,NaN,N,NaN,99.0,NaN,NaN,0.0,1.0,NaN,99.0,Y,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7567c7b8-e6fb-44c7-a1af-4ed3b5473236,D,CE4578001V,99.0,NaN,c2c6ee79-d930-4c8d-aa05-16af1419dd94
888278,0.0,NaN,0.0,NaN,N,NaN,99.0,NaN,NaN,0.0,1.0,NaN,99.0,Y,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0ab8d956-28ec-40f7-8c62-0a4a46499dd1,D,DA38720011,99.0,NaN,0dba0726-d614-4d9a-a97a-f46953470f8a
888279,2.0,NaN,0.0,NaN,N,NaN,99.0,NaN,NaN,0.0,1.0,NaN,0.0,Y,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0b8c5319-08ce-4ef8-b6fe-7d2f0891acf1,D,MCP22740011,99.0,NaN,24e08182-fdb3-4303-99b4-bfeb87d4261a
888280,1.0,NaN,99.0,NaN,N,NaN,99.0,NaN,NaN,99.0,99.0,NaN,0.0,N,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,553e00a2-131d-4c45-ac2e-392ddb677b86,D,MDTA1653000J,1.0,NaN,c8c0b963-e1c5-46d9-8c24-ea17a1fee68f
888281,2.0,NaN,0.0,NaN,N,NaN,99.0,NaN,NaN,0.0,1.0,NaN,0.0,Y,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,463e805c-1c23-4ffb-84f4-bafbe1603e26,D,ZR02350026,1.0,NaN,3ce7b6f9-2bd5-4a2c-96b7-91a8ef860d83
888282,5.0,NaN,0.0,NaN,N,NaN,99.0,NaN,NaN,0.0,0.0,NaN,99.0,Y,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,a8f17934-d60b-4d29-875e-3f907d182c41,D,DD56200003,99.0,NaN,935168c2-9588-466e-a3b5-b6ea849df332

How often did each severity of injury show up? (e.g. not injured, non-incapacitating injury, etc)

In [3]:
people.INJ_SEVER_CODE.value_counts()

1    716806
2     82642
3     76801
4     10353
5      1681
Name: INJ_SEVER_CODE, dtype: int64

We're only interested in fatalities, so let's create a new `is_fatality` column for when people received a fatal injury.

**Confirm there were 1681 people with fatal injuries.**

In [4]:
people['is_fatality'] = people.INJ_SEVER_CODE.replace({5: 1, 4: 0, 3:0, 2:0, 1:0})
people.head()

,AIRBAG_DEPLOYED,ALCOHOL_TESTTYPE_CODE,ALCOHOL_TEST_CODE,BAC_CODE,CDL_FLAG,CLASS,CONDITION_CODE,DATE_OF_BIRTH,DRUG_TESTRESULT_CODE,DRUG_TEST_CODE,EJECT_CODE,EMS_UNIT_LABEL,EQUIP_PROB_CODE,FAULT_FLAG,INJ_SEVER_CODE,LICENSE_STATE_CODE,MOVEMENT_CODE,OCC_SEAT_POS_CODE,PED_LOCATION_CODE,PED_OBEY_CODE,PED_TYPE_CODE,PED_VISIBLE_CODE,PERSON_ID,PERSON_TYPE,REPORT_NO,SAF_EQUIP_CODE,SEX_CODE,VEHICLE_ID,is_fatality
0,1.0,NaN,0.0,NaN,N,C,0.0,1952-04-20 00:00:00,NaN,0.0,1.0,NaN,1.0,N,1,PA,NaN,NaN,NaN,NaN,NaN,NaN,48dd00ee-e033-47e7-ad1e-0b734020301b,D,AB4284000S,13.0,F,eb6aadb8-dacb-4744-a1a7-ab812c96f27f,0
1,1.0,NaN,0.0,NaN,N,NaN,0.0,1985-05-28 00:00:00,NaN,0.0,0.0,NaN,0.0,N,1,MD,NaN,NaN,NaN,NaN,NaN,NaN,166296bd-ffd3-4c16-aa74-4f4bf4139d8d,D,AB4313000X,13.0,F,b463eb20-2f01-4200-9d6f-b18888ce2593,0
2,1.0,NaN,0.0,NaN,N,C,0.0,1960-10-04 00:00:00,NaN,0.0,0.0,NaN,0.0,Y,1,MD,NaN,NaN,NaN,NaN,NaN,NaN,f3b2743f-fbc3-4345-9419-56a0ca29102c,D,AB4313000X,13.0,F,3c8629d0-d524-47c1-bfbc-b18e07f3087e,0
3,1.0,NaN,0.0,NaN,N,B,0.0,1971-05-28 00:00:00,NaN,0.0,1.0,NaN,0.0,N,1,MD,NaN,NaN,NaN,NaN,NaN,NaN,5bbe589b-a2db-4dbb-be9b-17a800d69a08,D,AB4313000Y,0.0,F,c4628cdb-f295-4a24-8a4b-653741ac6ae7,0
4,1.0,NaN,0.0,NaN,N,D,0.0,1955-04-23 00:00:00,NaN,0.0,0.0,NaN,1.0,N,1,SC,NaN,NaN,NaN,NaN,NaN,NaN,b914136f-5ecd-46bb-94ec-ff5d4136c3eb,D,AB4669001F,13.0,F,cdda1580-fd79-4358-8819-c2250f494591,0

In [5]:
people['is_fatality'].value_counts()

0    886602
1      1681
Name: is_fatality, dtype: int64

## Working on Features

### Starting our analysis

We're going to run a regression on the impact of being **male vs female on crash fatalities**. Prepare a dataframe called `train_df` with the appropriate information in it.

* **Tip:** What column(s) are your input, and what is your output? Aka independent and dependent variables
* **Tip:** You'll need to convert your input column into something numeric, I suggest using `.replace`
* **Tip:** We aren't interested in the "Unknown" sex - either filtering or `np.nan` + `.dropna()` might be useful ways to get rid of those columns

In [6]:
people['genders'] = people.SEX_CODE.replace({'F': 1, 'M': 0, 'U': np.nan})
people['genders'].value_counts()

0.0    460973
1.0    354854
Name: genders, dtype: int64

In [7]:
train_df = people[['genders','is_fatality']]
train_df = train_df.dropna(subset=['genders'])
train_df.head()

   genders  is_fatality
0      1.0            0
1      1.0            0
2      1.0            0
3      1.0            0
4      1.0            0

Confirm that your `train_df` has two columns and 815,827 rows.

> **Tip:** If you have more rows, make sure you dropped all of the rows with Unknown sex.
>
> **Tip:** If you have more columns, make sure you only have your input and output columns.

In [8]:
train_df.shape

(815827, 2)

### Run your regression

See the effect of sex on whether the person's injuries are fatal or not. I want to see a result dataframe that includes:

* Feature name
* Coefficient
* Odds ratio

In [9]:
X = train_df.drop(columns=['is_fatality'])
y = train_df.is_fatality

In [10]:
clf = LogisticRegression(C=1e9, solver='lbfgs')
clf.fit(X, y)

LogisticRegression(C=1000000000.0, class_weight=None, dual=False,
                   fit_intercept=True, intercept_scaling=1, l1_ratio=None,
                   max_iter=100, multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [11]:
feature_names = X.columns
coefficients = clf.coef_[0]

pd.DataFrame({
    'feature': feature_names,
    'coefficient (log odds ratio)': coefficients,
    'odds ratio': np.exp(coefficients).round(4)
}).sort_values(by='odds ratio', ascending=False)

   feature  coefficient (log odds ratio)  odds ratio
0  genders                      -0.71481      0.4893

### Use words to interpret this result

In [12]:
# women are 50% less likely, aka men are twice as likely to get in car crashes

## Adding more features

The actual crash data has more details - whether it was snowy/icy, whether it was a highway, etc. 

Read in `combined-crash-data.csv` and merge it with our people dataset. I'll save you a lookup: the `REPORT_NO` is what matches between the two.

In [13]:
combined = pd.read_csv('combined-crash-data.csv')
combined.head()

/Users/lindseyfeingold/.pyenv/versions/3.7.1/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3049: DtypeWarning: Columns (27,30,33) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,ACC_DATE,ACC_TIME,AGENCY_CODE,AREA_CODE,COLLISION_TYPE_CODE,COUNTY_NO,C_M_ZONE_FLAG,DISTANCE,DISTANCE_DIR_FLAG,FEET_MILES_FLAG,FIX_OBJ_CODE,HARM_EVENT_CODE1,HARM_EVENT_CODE2,JUNCTION_CODE,LANE_CODE,LATITUDE,LIGHT_CODE,LOC_CODE,LOGMILE_DIR_FLAG,LOG_MILE,LONGITUDE,MAINROAD_NAME,MUNI_CODE,RD_COND_CODE,RD_DIV_CODE,REFERENCE_NO,REFERENCE_ROAD_NAME,REFERENCE_SUFFIX,REFERENCE_TYPE_CODE,REPORT_NO,REPORT_TYPE,ROUTE_TYPE_CODE,RTE_NO,RTE_SUFFIX,SIGNAL_FLAG,SURF_COND_CODE,WEATHER_CODE
0,2018-04-10 00:00:00,01:50:00,MSP,UNK,17,18.0,N,0.00,N,F,22.03,16.0,11.0,1.00,NaN,38.277230,4.0,NaN,N,2.09,-76.682876,NEWTOWNE NECK RD,0.0,1.0,1.0,166.0,ROSEBANK RD,NaN,CO,MSP6188002Q,Injury Crash,MD,243.0,NaN,N,2.0,6.01
1,2018-05-02 00:00:00,11:06:00,ELKTON,UNK,5,7.0,N,15.00,S,F,0.00,1.0,1.0,3.00,NaN,39.613747,1.0,NaN,N,19.41,-75.837454,N BRIDGE ST,52.0,1.0,3.0,362.0,LAUREL DR,NaN,MU,BK0227001M,Injury Crash,MD,213.0,NaN,N,2.0,6.01
2,2018-05-02 00:00:00,11:54:00,WASHINGTON,UNK,88,21.0,N,1.00,S,M,10.00,16.0,9.0,0.00,1.0,39.680144,1.0,NaN,N,2.60,-77.514781,RITCHIE RD,0.0,1.0,1.0,270.0,WISE RD,NaN,CO,ZU8005001W,Injury Crash,CO,269.0,NaN,N,2.0,6.01
3,2018-05-02 00:00:00,12:45:00,MONTGOMERY,UNK,7,15.0,N,0.00,E,F,0.00,1.0,1.0,2.00,2.0,39.015649,1.0,55122,E,0.00,-77.042728,FOREST GLEN RD,0.0,0.0,4.0,97.0,GEORGIA AVE,NaN,MD,MCP2891005S,Property Damage Crash,CO,697.0,NaN,Y,2.0,6.01
4,2018-05-02 00:00:00,12:02:00,MSP,UNK,11,8.0,N,0.15,N,M,0.00,1.0,1.0,9.04,2.0,38.620875,1.0,NaN,N,1.02,-76.901087,LEONARDTOWN RD,0.0,1.0,3.0,644.0,POST OFFICE RD,NaN,CO,MSP6743004Q,Property Damage Crash,MD,5.0,BU,N,2.0,6.01

In [14]:
merged = pd.merge(combined, people, on='REPORT_NO')
merged.head()

,ACC_DATE,ACC_TIME,AGENCY_CODE,AREA_CODE,COLLISION_TYPE_CODE,COUNTY_NO,C_M_ZONE_FLAG,DISTANCE,DISTANCE_DIR_FLAG,FEET_MILES_FLAG,FIX_OBJ_CODE,HARM_EVENT_CODE1,HARM_EVENT_CODE2,JUNCTION_CODE,LANE_CODE,LATITUDE,LIGHT_CODE,LOC_CODE,LOGMILE_DIR_FLAG,LOG_MILE,LONGITUDE,MAINROAD_NAME,MUNI_CODE,RD_COND_CODE,RD_DIV_CODE,REFERENCE_NO,REFERENCE_ROAD_NAME,REFERENCE_SUFFIX,REFERENCE_TYPE_CODE,REPORT_NO,REPORT_TYPE,ROUTE_TYPE_CODE,RTE_NO,RTE_SUFFIX,SIGNAL_FLAG,SURF_COND_CODE,WEATHER_CODE,AIRBAG_DEPLOYED,ALCOHOL_TESTTYPE_CODE,ALCOHOL_TEST_CODE,BAC_CODE,CDL_FLAG,CLASS,CONDITION_CODE,DATE_OF_BIRTH,DRUG_TESTRESULT_CODE,DRUG_TEST_CODE,EJECT_CODE,EMS_UNIT_LABEL,EQUIP_PROB_CODE,FAULT_FLAG,INJ_SEVER_CODE,LICENSE_STATE_CODE,MOVEMENT_CODE,OCC_SEAT_POS_CODE,PED_LOCATION_CODE,PED_OBEY_CODE,PED_TYPE_CODE,PED_VISIBLE_CODE,PERSON_ID,PERSON_TYPE,SAF_EQUIP_CODE,SEX_CODE,VEHICLE_ID,is_fatality,genders
0,2018-04-10 00:00:00,01:50:00,MSP,UNK,17,18.0,N,0.0,N,F,22.03,16.0,11.0,1.0,NaN,38.277230,4.0,NaN,N,2.09,-76.682876,NEWTOWNE NECK RD,0.0,1.0,1.0,166.0,ROSEBANK RD,NaN,CO,MSP6188002Q,Injury Crash,MD,243.0,NaN,N,2.0,6.01,4.0,2.0,3.0,NaN,N,C,2.0,1996-12-13 00:00:00,NaN,0.0,1.0,A,1.0,Y,3,MD,NaN,NaN,NaN,NaN,NaN,NaN,0212a82f-38a7-4a8a-969d-bce0920d3ab3,D,13.0,F,61d02432-7d40-401a-86ce-fea710234832,0,1.0
1,2018-05-02 00:00:00,11:06:00,ELKTON,UNK,5,7.0,N,15.0,S,F,0.00,1.0,1.0,3.0,NaN,39.613747,1.0,NaN,N,19.41,-75.837454,N BRIDGE ST,52.0,1.0,3.0,362.0,LAUREL DR,NaN,MU,BK0227001M,Injury Crash,MD,213.0,NaN,N,2.0,6.01,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1967-11-19 00:00:00,NaN,NaN,1.0,NaN,1.0,NaN,3,NaN,NaN,3.0,NaN,NaN,NaN,NaN,006b94ad-a347-4356-a48b-9b4b0849ae7b,O,13.0,F,089ece89-1c91-4fc4-a2f9-3368a8649a96,0,1.0
2,2018-05-02 00:00:00,11:06:00,ELKTON,UNK,5,7.0,N,15.0,S,F,0.00,1.0,1.0,3.0,NaN,39.613747,1.0,NaN,N,19.41,-75.837454,N BRIDGE ST,52.0,1.0,3.0,362.0,LAUREL DR,NaN,MU,BK0227001M,Injury Crash,MD,213.0,NaN,N,2.0,6.01,1.0,NaN,0.0,NaN,N,A,1.0,1992-06-12 00:00:00,NaN,0.0,1.0,NaN,1.0,N,1,DE,NaN,NaN,NaN,NaN,NaN,NaN,8d4526c4-2f46-4dae-bdeb-64cd811bda25,D,13.0,M,f583dc59-17b6-43cd-a853-c1be06240566,0,0.0
3,2018-05-02 00:00:00,11:06:00,ELKTON,UNK,5,7.0,N,15.0,S,F,0.00,1.0,1.0,3.0,NaN,39.613747,1.0,NaN,N,19.41,-75.837454,N BRIDGE ST,52.0,1.0,3.0,362.0,LAUREL DR,NaN,MU,BK0227001M,Injury Crash,MD,213.0,NaN,N,2.0,6.01,1.0,NaN,0.0,NaN,N,C,1.0,1954-08-18 00:00:00,NaN,0.0,1.0,B,1.0,N,3,MD,NaN,NaN,NaN,NaN,NaN,NaN,4fb7ba1d-4e1d-466c-a84c-de24d99ff7d0,D,13.0,M,089ece89-1c91-4fc4-a2f9-3368a8649a96,0,0.0
4,2018-05-02 00:00:00,11:06:00,ELKTON,UNK,5,7.0,N,15.0,S,F,0.00,1.0,1.0,3.0,NaN,39.613747,1.0,NaN,N,19.41,-75.837454,N BRIDGE ST,52.0,1.0,3.0,362.0,LAUREL DR,NaN,MU,BK0227001M,Injury Crash,MD,213.0,NaN,N,2.0,6.01,5.0,NaN,0.0,NaN,N,B,99.0,1948-04-23 00:00:00,NaN,0.0,1.0,A,1.0,Y,3,MD,NaN,NaN,NaN,NaN,NaN,NaN,a6ad59e0-a578-4093-a6df-99a66c936821,D,13.0,M,3326638d-db2b-416e-974c-fc385d6552b9,0,0.0

### Examining more possible features

How often was it wet, dry, snowy, icy, etc? **What was the most common condition?**

In [15]:
merged.SURF_COND_CODE.value_counts()

2.00     619569
1.00     147803
0.00      30921
3.00       9418
4.00       9111
99.00      3616
6.03       1697
88.00      1064
5.00        447
7.01        258
9.88        141
8.05         36
Name: SURF_COND_CODE, dtype: int64

Do you feel that a **Dry** road condition should be the average of **Wet** and **Snow?**

In [16]:
# no?

The answer to that should be *no*, which means we can't use this data as numeric data. We want a different coefficient for each of these - I want to know the impact of dry, the impact of wet, the impact of snow, all separately.

Start by **replacing each code with a proper description.** I'll even include them here:

* `00` - Not Applicable
* `01`	- Wet
* `02`	- Dry
* `03`	- Snow
* `04`	- Ice
* `05`	- Mud, Dirt, Gravel
* `06`	- Slush
* `07`	- Water (standing/moving)
* `08`	- Sand
* `09`	- Oil
* `88`	- Other
* `99`	- Unknown

But watch out, pandas read the column in as numbers so they might have come through a little differently than their codes.

In [17]:
merged['condition'] = merged.SURF_COND_CODE.replace({2.00 : 'Dry', 1.00 : 'Wet', 0.00 : 'Not Applicable', 4.00 : 'Ice', 3.00 : 'Snow', 6.03 : 'Slush', 99.00 : 'Unknown', 88.00 : 'Other', 5.00 : 'Mud, Dirt, Gravel', 7.01 : 'Water (standing/moving)', 9.88 : 'Oil', 8.05 : 'Sand'})
merged.head()

,ACC_DATE,ACC_TIME,AGENCY_CODE,AREA_CODE,COLLISION_TYPE_CODE,COUNTY_NO,C_M_ZONE_FLAG,DISTANCE,DISTANCE_DIR_FLAG,FEET_MILES_FLAG,FIX_OBJ_CODE,HARM_EVENT_CODE1,HARM_EVENT_CODE2,JUNCTION_CODE,LANE_CODE,LATITUDE,LIGHT_CODE,LOC_CODE,LOGMILE_DIR_FLAG,LOG_MILE,LONGITUDE,MAINROAD_NAME,MUNI_CODE,RD_COND_CODE,RD_DIV_CODE,REFERENCE_NO,REFERENCE_ROAD_NAME,REFERENCE_SUFFIX,REFERENCE_TYPE_CODE,REPORT_NO,REPORT_TYPE,ROUTE_TYPE_CODE,RTE_NO,RTE_SUFFIX,SIGNAL_FLAG,SURF_COND_CODE,WEATHER_CODE,AIRBAG_DEPLOYED,ALCOHOL_TESTTYPE_CODE,ALCOHOL_TEST_CODE,BAC_CODE,CDL_FLAG,CLASS,CONDITION_CODE,DATE_OF_BIRTH,DRUG_TESTRESULT_CODE,DRUG_TEST_CODE,EJECT_CODE,EMS_UNIT_LABEL,EQUIP_PROB_CODE,FAULT_FLAG,INJ_SEVER_CODE,LICENSE_STATE_CODE,MOVEMENT_CODE,OCC_SEAT_POS_CODE,PED_LOCATION_CODE,PED_OBEY_CODE,PED_TYPE_CODE,PED_VISIBLE_CODE,PERSON_ID,PERSON_TYPE,SAF_EQUIP_CODE,SEX_CODE,VEHICLE_ID,is_fatality,genders,condition
0,2018-04-10 00:00:00,01:50:00,MSP,UNK,17,18.0,N,0.0,N,F,22.03,16.0,11.0,1.0,NaN,38.277230,4.0,NaN,N,2.09,-76.682876,NEWTOWNE NECK RD,0.0,1.0,1.0,166.0,ROSEBANK RD,NaN,CO,MSP6188002Q,Injury Crash,MD,243.0,NaN,N,2.0,6.01,4.0,2.0,3.0,NaN,N,C,2.0,1996-12-13 00:00:00,NaN,0.0,1.0,A,1.0,Y,3,MD,NaN,NaN,NaN,NaN,NaN,NaN,0212a82f-38a7-4a8a-969d-bce0920d3ab3,D,13.0,F,61d02432-7d40-401a-86ce-fea710234832,0,1.0,Dry
1,2018-05-02 00:00:00,11:06:00,ELKTON,UNK,5,7.0,N,15.0,S,F,0.00,1.0,1.0,3.0,NaN,39.613747,1.0,NaN,N,19.41,-75.837454,N BRIDGE ST,52.0,1.0,3.0,362.0,LAUREL DR,NaN,MU,BK0227001M,Injury Crash,MD,213.0,NaN,N,2.0,6.01,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1967-11-19 00:00:00,NaN,NaN,1.0,NaN,1.0,NaN,3,NaN,NaN,3.0,NaN,NaN,NaN,NaN,006b94ad-a347-4356-a48b-9b4b0849ae7b,O,13.0,F,089ece89-1c91-4fc4-a2f9-3368a8649a96,0,1.0,Dry
2,2018-05-02 00:00:00,11:06:00,ELKTON,UNK,5,7.0,N,15.0,S,F,0.00,1.0,1.0,3.0,NaN,39.613747,1.0,NaN,N,19.41,-75.837454,N BRIDGE ST,52.0,1.0,3.0,362.0,LAUREL DR,NaN,MU,BK0227001M,Injury Crash,MD,213.0,NaN,N,2.0,6.01,1.0,NaN,0.0,NaN,N,A,1.0,1992-06-12 00:00:00,NaN,0.0,1.0,NaN,1.0,N,1,DE,NaN,NaN,NaN,NaN,NaN,NaN,8d4526c4-2f46-4dae-bdeb-64cd811bda25,D,13.0,M,f583dc59-17b6-43cd-a853-c1be06240566,0,0.0,Dry
3,2018-05-02 00:00:00,11:06:00,ELKTON,UNK,5,7.0,N,15.0,S,F,0.00,1.0,1.0,3.0,NaN,39.613747,1.0,NaN,N,19.41,-75.837454,N BRIDGE ST,52.0,1.0,3.0,362.0,LAUREL DR,NaN,MU,BK0227001M,Injury Crash,MD,213.0,NaN,N,2.0,6.01,1.0,NaN,0.0,NaN,N,C,1.0,1954-08-18 00:00:00,NaN,0.0,1.0,B,1.0,N,3,MD,NaN,NaN,NaN,NaN,NaN,NaN,4fb7ba1d-4e1d-466c-a84c-de24d99ff7d0,D,13.0,M,089ece89-1c91-4fc4-a2f9-3368a8649a96,0,0.0,Dry
4,2018-05-02 00:00:00,11:06:00,ELKTON,UNK,5,7.0,N,15.0,S,F,0.00,1.0,1.0,3.0,NaN,39.613747,1.0,NaN,N,19.41,-75.837454,N BRIDGE ST,52.0,1.0,3.0,362.0,LAUREL DR,NaN,MU,BK0227001M,Injury Crash,MD,213.0,NaN,N,2.0,6.01,5.0,NaN,0.0,NaN,N,B,99.0,1948-04-23 00:00:00,NaN,0.0,1.0,A,1.0,Y,3,MD,NaN,NaN,NaN,NaN,NaN,NaN,a6ad59e0-a578-4093-a6df-99a66c936821,D,13.0,M,3326638d-db2b-416e-974c-fc385d6552b9,0,0.0,Dry

Confirm you have 147,803 wet, and a few codes you can't understand, like `6.03` and `7.01`.

In [18]:
merged.condition.value_counts()

Dry                        619569
Wet                        147803
Not Applicable              30921
Snow                         9418
Ice                          9111
Unknown                      3616
Slush                        1697
Other                        1064
Mud, Dirt, Gravel             447
Water (standing/moving)       258
Oil                           141
Sand                           36
Name: condition, dtype: int64

Replace the codes you don't understand with `Other`.

In [19]:
merged['condition'] = merged.condition.replace({'Slush': 'Other', 'Water (standing/moving)' : 'Other', 'Sand' : 'Other', 'Oil': 'Other'})

Confirm you have 3,196 'Other'.

In [20]:
merged['condition'].value_counts()

Dry                  619569
Wet                  147803
Not Applicable        30921
Snow                   9418
Ice                    9111
Unknown                3616
Other                  3196
Mud, Dirt, Gravel       447
Name: condition, dtype: int64

## One-hot encoding

We're going to use `pd.get_dummies` to build a variable you'll call `surf_dummies`. Each surface condition should be a `0` or `1` as to whether it was that condition (dry, icy, wet, etc).

Use a `prefix=` so we know they are **surface** conditions.

You'll want to drop the column you'll use as the reference category.

**Before we do this: which column works best as the reference?**

In [21]:
pd.get_dummies(merged.condition, prefix='surface').head()

,surface_Dry,surface_Ice,"surface_Mud, Dirt, Gravel",surface_Not Applicable,surface_Other,surface_Snow,surface_Unknown,surface_Wet
0,1,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0
3,1,0,0,0,0,0,0,0
4,1,0,0,0,0,0,0,0

Now build your `surf_dummies` variable.

In [22]:
surf_dummies = pd.get_dummies(merged.condition, prefix='surface').drop('surface_Dry', axis=1)
surf_dummies.head()

,surface_Ice,"surface_Mud, Dirt, Gravel",surface_Not Applicable,surface_Other,surface_Snow,surface_Unknown,surface_Wet
0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0

Confirm your `surf_dummies` looks roughly like this:

|surface_Ice|Surce_Mud, Dirt, Gravel|surface_Not Applicable|...|surface_Wet|
|---|---|---|---|---|
|0|0|0|...|0|
|0|0|0|...|0|
|0|0|1|...|0|
|0|0|1|...|0|
|0|0|0|...|1|

## Another regression

Let's run another regression to see the impact of both **sex and surface condition** on fatalities.

### Build your `train_df`

To build your `train_df`, I recommend doing it either of these two ways:

```python
train_df = pd.DataFrame({
    'col1': merged.col1,
    'col2': merged.col2,
    'col3': merged.col3,
})
train_df = train_df.join(surf_dummies)
train_df = train_df.dropna()
```

or like this:

```python
train_df = train_df[['col1','col2','col3']].copy()
train_df = train_df.join(surf_dummies)
train_df = train_df.dropna()
```

The second one is shorter, but the first one makes it easier to use comments to remove columns later.

In [23]:
train_df = pd.DataFrame({
   'is_fatality': merged['is_fatality'],
   'genders': merged['genders'],
   'condition': merged['condition'],
})

train_df = merged[['is_fatality', "condition"]].join(surf_dummies)
train_df = train_df.dropna()

In [24]:
train_df = merged[['is_fatality', "genders"]].join(surf_dummies)
train_df = train_df.dropna()

### Run your regression and check your odds ratios

Actually no, wait, first - what kind of surface do you think will have the **highest fatality rate?**

In [25]:
# snow?

In [26]:
X = train_df.drop(columns=['is_fatality'])
y = train_df.is_fatality

In [27]:
clf = LogisticRegression(C=1e9, solver='lbfgs')
clf.fit(X, y)

LogisticRegression(C=1000000000.0, class_weight=None, dual=False,
                   fit_intercept=True, intercept_scaling=1, l1_ratio=None,
                   max_iter=100, multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [28]:
feature_names = X.columns
coefficients = clf.coef_[0]

pd.DataFrame({
    'feature': feature_names,
    'coefficient (log odds ratio)': coefficients,
    'odds ratio': np.exp(coefficients).round(4)
}).sort_values(by='odds ratio', ascending=False)

                     feature  coefficient (log odds ratio)  odds ratio
2  surface_Mud, Dirt, Gravel                      1.115150      3.0500
4              surface_Other                      0.596230      1.8153
6            surface_Unknown                      0.340200      1.4052
7                surface_Wet                     -0.098825      0.9059
1                surface_Ice                     -0.557708      0.5725
5               surface_Snow                     -0.652480      0.5208
0                    genders                     -0.718133      0.4877
3     surface_Not Applicable                     -0.730582      0.4816

Confirm your `train_df` has 815,843 rows and 9 columns.

* **Tip:** When you run your regression, if you get an error about not knowing what to do with `U`, it's because you didn't convert your sex to numbers (or if you did, you didn't do it in your original dataframe)

In [29]:
train_df.shape

(815843, 9)

**Is this what you expected?** Why do you think this result might be the case?

# More features: Vehicles

Maybe the car they're in is related to the car they were in. Luckily, we have this information - **read in `combined_vehicle_data` as `vehicles`.**

In [30]:
vehicles = pd.read_csv('combined-vehicle-data.csv')
vehicles.head()

,AREA_DAMAGED_CODE1,AREA_DAMAGED_CODE2,AREA_DAMAGED_CODE3,AREA_DAMAGED_CODE_IMP1,AREA_DAMAGED_CODE_MAIN,BODY_TYPE_CODE,COMMERCIAL_FLAG,CONTI_DIRECTION_CODE,CV_BODY_TYPE_CODE,DAMAGE_CODE,DRIVERLESS_FLAG,FIRE_FLAG,GOING_DIRECTION_CODE,GVW_CODE,HARM_EVENT_CODE,HAZMAT_SPILL_FLAG,HIT_AND_RUN_FLAG,HZM_NUM,MOVEMENT_CODE,NUM_AXLES,PARKED_FLAG,REPORT_NO,SPEED_LIMIT,TOWED_AWAY_FLAG,TOWED_VEHICLE_CONFIG_CODE,VEHICLE_ID,VEH_MAKE,VEH_MODEL,VEH_YEAR,VIN_NO
0,8.0,9.0,10.0,10.0,10.0,23.08,N,E,NaN,5,N,N,E,NaN,9.0,NaN,N,NaN,1.0,NaN,N,ADJ487004H,30,Y,0,000238fd-44fa-4cd5-8eb7-41ab30500bec,CHEVY,TAHOE,2005.0,1GNEK13Q2J285593
1,12.0,NaN,NaN,12.0,12.0,2.00,N,E,NaN,4,N,N,E,NaN,1.0,NaN,N,NaN,1.0,NaN,N,MCP2487000M,40,Y,0,00038116-1bf9-48cc-b317-4f4375d14b60,INFI,4S,2003.0,JNKCV51E63M013580
2,6.0,7.0,NaN,6.0,6.0,20.00,N,N,NaN,3,N,N,N,NaN,1.0,NaN,N,NaN,6.0,NaN,N,CB5190006B,55,N,0,0003b659-2785-4868-8877-0b786a284827,TOYT,TK,2011.0,5TFUY5F1XBX167340
3,8.0,NaN,NaN,8.0,8.0,2.00,N,W,NaN,2,N,NaN,W,NaN,1.0,NaN,N,NaN,8.0,NaN,N,ADJ4590035,5,N,0,00050484-d08f-4b6e-bc7e-9ec270e94660,HONDA,CIVIC,2015.0,2HGFG4A59FH702545
4,12.0,NaN,NaN,12.0,12.0,2.00,N,N,NaN,4,N,NaN,N,NaN,0.0,NaN,N,NaN,1.0,NaN,N,ADJ849000Z,10,N,0,00057af4-d848-4cee-b854-707f57581f4e,HONDA,ACCORD,2003.0,1HGCM66313A037175

## Weights of those cars

The car weights are stored in **another file** since the info had to come from an API. I looked up the VINs - vehicle identification numbers - in a government database to try to get data for each of them.

**Read them and build a new dataframe that is both the vehicle data along with their weights.** You can call it `vehicles` since you don't need the original weightless vehicle data any more.

In [31]:
vins_and_weights = pd.read_csv('vins_and_weights.csv')
vins_and_weights.head()

                 VIN       Make     Model  ModelYear  weight
0  2FMDA5143TBB45576       FORD  WINDSTAR       1996  3733.0
1  2G1WC5E37E1120089  CHEVROLET    IMPALA       2014  3618.0
2  5J6RE4H55AL053951      HONDA      CR-V       2010  3389.0
3  1N4AA5AP0EC435185     NISSAN    MAXIMA       2014  3556.0
4  JTHCK262075010440      LEXUS        IS       2007  3527.0

In [32]:
vehicles1 = pd.merge(vehicles, vins_and_weights, left_on='VIN_NO', right_on='VIN')
vehicles1.head()

,AREA_DAMAGED_CODE1,AREA_DAMAGED_CODE2,AREA_DAMAGED_CODE3,AREA_DAMAGED_CODE_IMP1,AREA_DAMAGED_CODE_MAIN,BODY_TYPE_CODE,COMMERCIAL_FLAG,CONTI_DIRECTION_CODE,CV_BODY_TYPE_CODE,DAMAGE_CODE,DRIVERLESS_FLAG,FIRE_FLAG,GOING_DIRECTION_CODE,GVW_CODE,HARM_EVENT_CODE,HAZMAT_SPILL_FLAG,HIT_AND_RUN_FLAG,HZM_NUM,MOVEMENT_CODE,NUM_AXLES,PARKED_FLAG,REPORT_NO,SPEED_LIMIT,TOWED_AWAY_FLAG,TOWED_VEHICLE_CONFIG_CODE,VEHICLE_ID,VEH_MAKE,VEH_MODEL,VEH_YEAR,VIN_NO,VIN,Make,Model,ModelYear,weight
0,8.0,9.0,10.0,10.0,10.0,23.08,N,E,NaN,5,N,N,E,NaN,9.0,NaN,N,NaN,1.0,NaN,N,ADJ487004H,30,Y,0,000238fd-44fa-4cd5-8eb7-41ab30500bec,CHEVY,TAHOE,2005.0,1GNEK13Q2J285593,1GNEK13Q2J285593,CHEVROLET,GMT-400,1988,4300.0
1,12.0,NaN,NaN,12.0,12.0,2.00,N,E,NaN,4,N,N,E,NaN,1.0,NaN,N,NaN,1.0,NaN,N,MCP2487000M,40,Y,0,00038116-1bf9-48cc-b317-4f4375d14b60,INFI,4S,2003.0,JNKCV51E63M013580,JNKCV51E63M013580,INFINITI,G35,2003,3468.0
2,6.0,7.0,NaN,6.0,6.0,20.00,N,N,NaN,3,N,N,N,NaN,1.0,NaN,N,NaN,6.0,NaN,N,CB5190006B,55,N,0,0003b659-2785-4868-8877-0b786a284827,TOYT,TK,2011.0,5TFUY5F1XBX167340,5TFUY5F1XBX167340,TOYOTA,TUNDRA,2011,5480.0
3,8.0,NaN,NaN,8.0,8.0,2.00,N,W,NaN,2,N,NaN,W,NaN,1.0,NaN,N,NaN,8.0,NaN,N,ADJ4590035,5,N,0,00050484-d08f-4b6e-bc7e-9ec270e94660,HONDA,CIVIC,2015.0,2HGFG4A59FH702545,2HGFG4A59FH702545,HONDA,CIVIC,2015,2754.0
4,12.0,NaN,NaN,12.0,12.0,2.00,N,N,NaN,4,N,NaN,N,NaN,0.0,NaN,N,NaN,1.0,NaN,N,ADJ849000Z,10,N,0,00057af4-d848-4cee-b854-707f57581f4e,HONDA,ACCORD,2003.0,1HGCM66313A037175,1HGCM66313A037175,HONDA,ACCORD,2003,3023.0

Confirm that your combined `vehicles` dataset should have 534,436 rows and 35 columns. And yes, that's less than we were working with before - you haven't combined it with the people/crashes dataset yet.

In [33]:
vehicles1.shape

(534436, 35)

### Filter your data

We only want vehicles that are "normal" - somewhere between 1500 and 6000 pounds. Filter your vehicles to only include those in that weight range.

In [34]:
vehicles2 = vehicles1[(vehicles1['weight']>1500) & (vehicles1['weight']<6000)]
vehicles2.sort_values(by='weight')

,AREA_DAMAGED_CODE1,AREA_DAMAGED_CODE2,AREA_DAMAGED_CODE3,AREA_DAMAGED_CODE_IMP1,AREA_DAMAGED_CODE_MAIN,BODY_TYPE_CODE,COMMERCIAL_FLAG,CONTI_DIRECTION_CODE,CV_BODY_TYPE_CODE,DAMAGE_CODE,DRIVERLESS_FLAG,FIRE_FLAG,GOING_DIRECTION_CODE,GVW_CODE,HARM_EVENT_CODE,HAZMAT_SPILL_FLAG,HIT_AND_RUN_FLAG,HZM_NUM,MOVEMENT_CODE,NUM_AXLES,PARKED_FLAG,REPORT_NO,SPEED_LIMIT,TOWED_AWAY_FLAG,TOWED_VEHICLE_CONFIG_CODE,VEHICLE_ID,VEH_MAKE,VEH_MODEL,VEH_YEAR,VIN_NO,VIN,Make,Model,ModelYear,weight
97180,6.0,7.0,NaN,7.0,7.0,2.00,N,NaN,NaN,3,Y,N,NaN,NaN,2.0,NaN,N,NaN,10.00,NaN,Y,ADG902000T,0,N,0,42055bd3-9ce7-4f60-8643-ffac4c9fe25e,GEO,METRO,1980.0,2C1MR6467M6792313,2C1MR6467M6792313,GEO,METRO,1991,1701.0
59842,1.0,11.0,12.0,12.0,12.0,2.00,N,W,NaN,5,N,N,W,NaN,9.0,NaN,N,NaN,1.00,NaN,N,MCP2564000Q,35,Y,0,71b323a9-1c67-4c06-8a38-7167915567db,GEO,METRO,1992.0,2C1MR2464N6705980,2C1MR2464N6705980,GEO,METRO,1992,1701.0
233396,6.0,12.0,NaN,6.0,6.0,2.00,N,NaN,NaN,3,Y,NaN,NaN,NaN,0.0,NaN,N,NaN,10.00,NaN,Y,AE5277000V,30,N,0,bfba35b1-39aa-43d9-92d6-9278d04c10cd,GEO,METRO,1991.0,2C1MR6463M6742413,2C1MR6463M6742413,GEO,METRO,1991,1701.0
339961,12.0,NaN,NaN,12.0,12.0,2.00,N,E,NaN,4,N,N,E,NaN,1.0,NaN,N,NaN,1.00,NaN,N,MSP617100F2,55,Y,0,9f073ce1-94a9-4429-92cd-299ff2467e84,GEO,METRO,1991.0,2C1MR2468M6702028,2C1MR2468M6702028,GEO,METRO,1991,1701.0
436224,6.0,NaN,NaN,6.0,6.0,2.00,N,W,NaN,2,N,N,W,NaN,1.0,NaN,N,NaN,4.00,NaN,N,ADJ6960002,35,Y,0,1e960d5d-9ce5-4a48-886f-2a455b937b4a,CHEVROLET,GEO,1994.0,2C1MR2469R6770796,2C1MR2469R6770796,GEO,METRO,1994,1779.0
43038,1.0,2.0,12.0,12.0,1.0,2.00,N,W,NaN,4,N,N,W,NaN,1.0,NaN,N,NaN,3.00,NaN,N,ADJ323000Q,35,Y,0,1cca948a-43da-45b5-9f38-b3931e932e7e,GEO,METRO,1994.0,2C1MS2463R6701901,2C1MS2463R6701901,GEO,METRO,1994,1779.0
212696,5.0,6.0,7.0,6.0,6.0,2.00,N,W,NaN,3,N,N,W,NaN,1.0,NaN,N,NaN,1.00,NaN,N,DA39490017,30,N,0,3635e246-80f4-4e47-9ed3-8b67feea4265,GEO,2S,1994.0,2C1MR2466R6753597,2C1MR2466R6753597,GEO,METRO,1994,1779.0
219785,11.0,NaN,NaN,11.0,11.0,2.00,N,S,NaN,3,N,N,S,NaN,1.0,NaN,N,NaN,1.00,NaN,N,MSP47970022,50,N,0,652c540d-b7ea-4799-a68f-9dab7694f8bf,GEO,METRO,1997.0,2C1MR2296V6769676,2C1MR2296V6769676,GEO,METRO,1997,1832.0
260486,1.0,11.0,12.0,12.0,12.0,2.00,N,N,NaN,5,N,N,N,NaN,1.0,NaN,N,NaN,1.00,NaN,N,MSP6491001F,50,N,0,6753f811-03b6-4dda-b0f0-5b15ef692643,GEO,METRO,1997.0,2C1MR2296V6749279,2C1MR2296V6749279,GEO,METRO,1997,1832.0
14291,6.0,NaN,NaN,6.0,6.0,2.00,N,E,NaN,4,N,N,E,NaN,1.0,NaN,N,NaN,19.07,NaN,N,MSP5747008D,35,Y,0,53e490a9-08df-4ebd-8921-0ec31620de23,GEO,METRO,1997.0,2C1MR2292V6755726,2C1MR2292V6755726,GEO,METRO,1997,1832.0
183315,1.0,11.0,12.0,12.0,12.0,2.00,N,S,NaN,4,N,N,S,NaN,1.0,NaN,N,NaN,1.00,NaN,N,AE38040022,40,Y,0,74e957f1-1989-48b7-a7fa-a0e66ba2210c,GEO,2S,1997.0,2C1MR2290V6767292,2C1MR2290V6767292,GEO,METRO,1997,1832.0
125719,3.0,4.0,18.0,3.0,3.0,2.00,N,W,NaN,4,N,N,W,NaN,11.0,NaN,N,NaN,1.00,NaN,N,AC2038000Z,35,Y,0,fb495c18-0029-4afc-87f1-bf6b6a3b4fef,GEO,METRO,1997.0,2C1MR2292V6743589,2C1MR2292V6743589,GEO,METRO,1997,1832.0
389433,4.0,5.0,6.0,3.0,4.0,2.00,N,E,NaN,4,N,N,E,NaN,1.0,NaN,N,NaN,12.00,NaN,N,CD0617002B,50,Y,0,e8213c9a-94b6-436d-826f-fc864cb2b41f,GEO,METRO,1997.0,2C1MR5290V6725495,2C1MR5290V6725495,GEO,METRO,1997,1832.0
415882,1.0,11.0,12.0,12.0,12.0,2.00,N,N,NaN,5,N,N,N,NaN,9.0,NaN,N,NaN,20.03,NaN,N,MSP45900021,25,Y,0,93c9845f-8cd4-41ed-8624-15a55b8d434c,GEO,METRO,1997.0,2C1MR529XV6759122,2C1MR529XV6759122,GEO,METRO,1997,1832.0
54746,6.0,7.0,NaN,6.0,6.0,2.00,N,NaN,NaN,4,Y,N,NaN,NaN,1.0,NaN,N,NaN,10.00,NaN,Y,AC1274001N,25,N,0,583f893a-f3c5-4b2f-b580-0972e87a2047,CHEV,GEO,1997.0,2C1MR5294V6750058,2C1MR5294V6750058,GEO,METRO,1997,1832.0
381685,12.0,NaN,NaN,12.0,12.0,2.00,N,S,NaN,3,N,N,W,NaN,9.0,NaN,N,NaN,12.00,NaN,N,AC2159003D,30,Y,0,b171c889-755b-4746-aa4a-5eb8e4b942d5,SMART CAR,2D,2014.0,WMEEJ3BA2EK772121,WMEEJ3BA2EK772121,SMART,FORTWO,2014,1852.0
322610,6.0,12.0,18.0,98.0,12.0,2.00,N,S,NaN,4,N,NaN,S,NaN,11.0,NaN,N,NaN,1.00,NaN,N,AE58690031,30,Y,0,38ae2b2e-f05f-409e-96fe-3b63a6ab7136,SMARTCAR,2D,2014.0,WMEEJ3BA2EK772863,WMEEJ3BA2EK772863,SMART,FORTWO,2014,1852.0
49179,NaN,NaN,NaN,6.0,6.0,2.00,N,S,NaN,1,N,N,W,NaN,0.0,NaN,N,NaN,3.00,NaN,N,MCP2951000W,40,N,0,3c04b886-bbdb-4cf8-a294-5a454a3c4971,SMART,2D,2014.0,WMEEJ3BA1EK771509,WMEEJ3BA1EK771509,SMART,FORTWO,2014,1852.0
96791,1.0,11.0,12.0,12.0,12.0,2.00,N,N,NaN,4,N,N,W,NaN,9.0,NaN,N,NaN,12.00,NaN,N,MCP3010000M,40,Y,0,3f73d21a-5275-4308-a99b-a7eef10c090f,SMRT,2S,2014.0,WMEEJ3BAXEK749007,WMEEJ3BAXEK749007,SMART,FORTWO,2014,1852.0
412334,4.0,6.0,8.0,6.0,6.0,2.00,N,S,NaN,3,N,NaN,S,NaN,1.0,NaN,N,NaN,3.00,NaN,N,AC18330017,50,N,0,7d71bd50-1093-4bb7-bb47-676c1399102b,GEO,METRO,1995.0,2C1MR2265S6781786,2C1MR2265S6781786,GEO,METRO,1995,1857.0
130186,2.0,2.0,NaN,2.0,2.0,2.00,N,N,NaN,4,N,N,N,NaN,1.0,NaN,N,NaN,1.00,NaN,N,ZG07710009,35,Y,0,17390ff5-5719-4624-ab12-ce391a043820,GEO,4S,1995.0,2C1MR5296S6783073,2C1MR5296S6783073,GEO,METRO,1995,1857.0
432627,7.0,8.0,NaN,8.0,8.0,2.00,N,W,NaN,2,N,N,W,NaN,0.0,NaN,N,NaN,12.00,NaN,N,AE57810009,25,N,0,01af5d78-5fc2-4769-a8eb-47c0828cd8cf,FORD,FEISTA,1993.0,KNJPT05HXP6111230,KNJPT05HXP6111230,FORD,FESTIVA,1993,1872.0
75784,1.0,11.0,12.0,12.0,12.0,2.00,N,S,NaN,5,N,N,N,NaN,1.0,NaN,N,NaN,3.00,NaN,N,DA2260000P,45,N,0,c5bfcec6-5f61-4a70-b84c-f7f1f6ce6fcc,FORD,FIESTA,1992.0,KNJPT06H5N6106237,KNJPT06H5N6106237,FORD,FESTIVA,1992,1872.0
427134,1.0,NaN,NaN,1.0,1.0,2.00,N,W,NaN,3,N,N,W,NaN,1.0,NaN,N,NaN,3.00,NaN,N,MSP1926002R,50,N,0,dd0891a9-10e6-47b3-8c8b-02a3081ad6d0,FORD,FESTVIA,1989.0,KNJBT06K9K6108722,KNJBT06K9K6108722,FORD,FESTIVA,1989,1872.0
80651,8.0,9.0,10.0,10.0,10.0,2.00,N,N,NaN,99,N,N,N,NaN,1.0,NaN,Y,NaN,7.00,NaN,N,DA3425000N,40,N,0,dfd9b1e7-2861-4429-a953-74182b582155,FORD,FIESTA,1993.0,KNJPT05HXP6101037,KNJPT05HXP6101037,FORD,FESTIVA,1993,1872.0
443873,1.0,12.0,12.0,2.0,2.0,2.00,N,E,NaN,4,N,N,E,NaN,1.0,NaN,N,NaN,2.00,NaN,N,CD0632000G,50,Y,0,5ba1a8da-1911-4d4c-adde-2e6becd38ce4,SUZUKI,2D HACHBAK,1997.0,2S2AB21H9V6600499,2S2AB21H9V6600499,SUZUKI,SWIFT,1997,1878.0
409830,12.0,NaN,NaN,12.0,12.0,2.00,N,S,NaN,4,N,N,S,NaN,0.0,NaN,N,NaN,1.00,NaN,N,AE5509000X,35,Y,0,6d462ac0-c1b5-48c0-a48a-fafa0e78e715,CHEVY,METRO,1999.0,2C1MR2261X6714562,2C1MR2261X6714562,CHEVROLET,METRO,1999,1928.0
312707,1.0,11.0,12.0,12.0,12.0,2.00,N,N,NaN,4,N,N,N,NaN,2.0,NaN,N,NaN,1.00,NaN,N,EK5814000S,25,Y,0,a291dc32-6607-4372-b1e9-927b592c6a48,CHEV,4S,2000.0,2C1MR5226Y6718980,2C1MR5226Y6718980,CHEVROLET,METRO,2000,1928.0
96841,6.0,12.0,NaN,12.0,12.0,2.00,N,N,NaN,4,N,N,N,NaN,1.0,NaN,N,NaN,3.00,NaN,N,ZD5855001N,55,Y,0,3fd2db34-5168-453f-ba08-68a1caf646cd,CHEVY,METRO,2000.0,2C1MR2222Y6701687,2C1MR2222Y6701687,CHEVROLET,METRO,2000,1928.0
529968,10.0,11.0,12.0,9.0,11.0,2.00,N,NaN,NaN,4,Y,NaN,NaN,NaN,1.0,NaN,N,NaN,10.00,NaN,Y,MSP5622006G,65,Y,0,d19eefcb-8834-44f2-b8ab-383308a2e3f4,CHEVY,METRO,1998.0,2C1MR5222W6702482,2C1MR5222W6702482,CHEVROLET,METRO,1998,1928.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8595,1.0,2.0,NaN,1.0,1.0,23.08,N,W,NaN,3,N,N,W,NaN,1.0,NaN,N,NaN,1.00,NaN,N,BJ0155007Y,35,N,0,324082b7-3ee8-4206-93bc-ad1aa542ea03,TOYOTA,SEQUOIA,2017.0,5TDBY5G19HS154390,5TDBY5G19HS154390,TOYOTA,SEQUOIA,2017,5985.0
389723,99.0,NaN,NaN,7.0,7.0,23.08,N,NaN,NaN,99,Y,N,NaN,NaN,1.0,NaN,N,NaN,10.00,NaN,Y,ADI945003V,25,N,0,ea59610b-af20-465b-8298-0fba5969587a,TOYOTA,SEQUOIA,2016.0,5TDJY5G14GS140939,5TDJY5G14GS140939,TOYOTA,SEQUOIA,2016,5985.0
359041,1.0,2.0,3.0,1.0,1.0,23.08,N,E,NaN,3,N,N,E,NaN,9.0,NaN,N,NaN,1.00,NaN,N,AE54490010,30,N,0,13bc9668-ceca-4f0e-9c07-b5712fe74d20,TOYOTA,SEQUIA,2014.0,5TDDY5G11ES102871,5TDDY5G11ES102871,TOYOTA,SEQUOIA,2014,5985.0
499530,2.0,3.0,4.0,3.0,4.0,2.00,N,E,NaN,2,N,NaN,E,NaN,8.0,NaN,N,NaN,1.00,NaN,N,ADJ606001P,25,N,0,f394cd78-1601-41db-b0c7-7faf1f633f40,TOYOTA,SEQUOIA,2013.0,5TDDY5G10DS080084,5TDDY5G10DS080084,TOYOTA,SEQUOIA,2013,5985.0
376813,12.0,NaN,NaN,12.0,12.0,23.08,N,E,NaN,4,N,N,E,NaN,1.0,NaN,N,NaN,3.00,NaN,N,CB59070027,50,Y,0,8fa2a8ca-57bb-4eb9-b1a7-b9c454081840,TOYOTA,SEQUOIA,2016.0,5TDDY5G16GS146402,5TDDY5G16GS146402,TOYOTA,SEQUOIA,2016,5985.0
316885,5.0,6.0,NaN,6.0,6.0,22.05,N,NaN,NaN,3,N,N,NaN,NaN,1.0,NaN,N,NaN,10.00,NaN,Y,RD00770033,20,N,0,bcaeefc1-4601-43ef-af17-70d36c79b2ba,TOYOTA,TRUCK,2015.0,5TDJY5G14FS125663,5TDJY5G14FS125663,TOYOTA,SEQUOIA,2015,5985.0
456382,6.0,6.0,6.0,6.0,6.0,23.08,N,E,NaN,3,N,N,E,NaN,1.0,NaN,N,NaN,4.00,NaN,N,ZJ0433000B,40,N,0,c21e094d-1926-43c7-8496-4a0c38d2f597,TOYOTA,SEQUOIA,2013.0,5TDBY5614DS076255,5TDBY5614DS076255,TOYOTA,SEQUOIA,2013,5985.0
310618,8.0,NaN,NaN,8.0,8.0,2.00,N,NaN,NaN,3,Y,NaN,NaN,NaN,0.0,NaN,N,NaN,10.00,NaN,Y,AE58850015,0,N,0,95e9f64e-c744-4195-a6d2-cc9dd2000a4a,TOYOTA,SEQUOIA,2016.0,5TDBY5G10GS141137,5TDBY5G10GS141137,TOYOTA,SEQUOIA,2016,5985.0
310619,12.0,NaN,NaN,12.0,12.0,2.00,N,E,NaN,4,N,N,E,NaN,1.0,NaN,N,NaN,3.00,NaN,N,MSP6685005Y,55,Y,0,b8fe29a8-9f51-4011-aa66-cfd9ab50c794,TOYOTA,4RUNNER,2016.0,5TDBY5G10GS141137,5TDBY5G10GS141137,TOYOTA,SEQUOIA,2016,5985.0
183405,5.0,6.0,NaN,5.0,5.0,23.08,N,NaN,NaN,3,Y,N,NaN,NaN,1.0,NaN,N,NaN,10.00,NaN,Y,AE51480024,10,N,0,75785c9c-38e4-43fd-ae15-2c1d3a784ae9,TOYOTA,SEQUOIA,2016.0,5TDJY5G19GS144470,5TDJY5G19GS144470,TOYOTA,SEQUOIA,2016,5985.0
503871,6.0,NaN,NaN,6.0,6.0,2.00,N,S,NaN,3,N,N,S,NaN,1.0,NaN,N,NaN,3.00,NaN,N,MCP20390027,45,U,0,1053a354-4ba8-4f09-ac11-0e3b78c67238,TOYOTA,SEQUOIA,2016.0,5TDJY5G14GS142707,5TDJY5G14GS142707,TOYOTA,SEQUOIA,2016,5985.0
185700,6.0,6.0,NaN,6.0,6.0,23.08,N,N,NaN,3,N,N,N,NaN,1.0,NaN,N,NaN,6.00,NaN,N,DA40610007,45,N,0,844334a7-efe5-47b6-a0ca-01a880497989,TOYT,TK,2014.0,5TDBY5G10ES108443,5TDBY5G10ES108443,TOYOTA,SEQUOIA,2014,5985.0
259972,12.0,NaN,NaN,12.0,12.0,2.00,N,W,NaN,3,N,N,W,NaN,1.0,NaN,N,NaN,1.00,NaN,N,DA3995000Q,35,N,0,6474ba48-7118-4c23-9404-2328c09d9fe7,TOYOTA,SEQUOIA,2013.0,5TDBY5G17DS090618,5TDBY5G17DS090618,TOYOTA,SEQUOIA,2013,5985.0
381621,5.0,6.0,NaN,5.0,5.0,23.08,N,W,NaN,2,N,N,W,NaN,1.0,NaN,N,NaN,9.00,NaN,N,AE44920007,0,N,0,b0fd814d-4887-48e6-975f-82ce4fdbe91f,TOYOTA,SEQUOIA,2014.0,5TDDY5G12ES103172,5TDDY5G12ES103172,TOYOTA,SEQUOIA,2014,5985.0
489581,12.0,NaN,NaN,12.0,12.0,23.08,N,S,NaN,2,N,N,W,NaN,1.0,NaN,N,NaN,12.00,NaN,N,DE7191000K,30,N,0,aebacec9-4af3-4267-a0bf-9a726cd6a51c,TOYOTA,SEQUOIA,2013.0,5TDDY5G18DS079281,5TDDY5G18DS079281,TOYOTA,SEQUOIA,2013,5985.0
238429,11.0,12.0,NaN,12.0,12.0,23.08,N,N,NaN,4,N,N,N,NaN,1.0,NaN,N,NaN,1.00,NaN,N,MSP5096001T,30,Y,0,e1d4c4f5-aea8-4947-bcb0-e18d8463c10e,TOYOTA,SEQUIOA,2013.0,5TDDY5G13DS089992,5TDDY5G13DS089992,TOYOTA,SEQUOIA,2013,5985.0
515351,11.0,NaN,NaN,11.0,11.0,2.00,N,N,NaN,2,N,NaN,N,NaN,1.0,NaN,N,NaN,1.00,NaN,N,ADJ5980019,45,N,0,597eb90d-207c-4161-b8ae-ff4878cb836c,TOYOTA,TK,2016.0,5TDBY5G17GS140213,5TDBY5G17GS140213,TOYOTA,SEQUOIA,2016,5985.0
280850,1.0,2.0,3.0,1.0,2.0,2.00,N,S,NaN,3,N,N,S,NaN,1.0,NaN,N,NaN,3.00,NaN,N,MSP6582004Q,55,N,0,df74ae7c-3dbc-417e-9b77-ddb50158ecf6,TOYOTA,SEQUOIA,2014.0,5TDBY5G15ES100452,5TDBY5G15ES100452,TOYOTA,SEQUOIA,2014,5985.0
501350,7.0,8.0,NaN,8.0,8.0,23.08,N,W,NaN,2,N,N,W,NaN,1.0,NaN,N,NaN,1.00,NaN,N,ADI519003P,30,N,0,0055ccd8-dc19-4f58-9f9b-bc0a6671de29,TOYOTA,SEQUOIA,2015.0,5TDBY5G10FS118939,5TDBY5G10FS118939,TOYOTA,SEQUOIA,2015,5985.0
291401,6.0,NaN,NaN,6.0,6.0,23.08,N,E,NaN,3,N,N,E,NaN,1.0,NaN,N,NaN,3.00,NaN,N,MSP47530006,55,N,0,1e570cc5-a4a5-4457-8d61-7610f9e51fcd,TOYOTA,SEQUOIA,2015.0,5TDDY5G18FS118308,5TDDY5G18FS118308,TOYOTA,SEQUOIA,2015,5985.0
30451,11.0,12.0,NaN,11.0,11.0,23.08,N,N,NaN,3,N,N,N,NaN,1.0,NaN,N,NaN,1.00,NaN,N,MSP6826007K,55,N,0,b507818b-84e1-4541-9b28-3939adedf51a,TOYOTA,SEQUOIA,2016.0,5TDBY5G19GS141508,5TDBY5G19GS141508,TOYOTA,SEQUOIA,2016,5985.0
172777,12.0,NaN,NaN,12.0,12.0,2.00,N,N,NaN,5,N,Y,N,NaN,1.0,NaN,N,NaN,1.00,NaN,N,ADJ685002W,45,N,0,30a7fb3e-3894-4c2d-a401-c40109445bdd,TOYOTA,SEQUOIA,2014.0,5TDDY5G13ES109417,5TDDY5G13ES109417,TOYOTA,SEQUOIA,2014,5985.0
220429,9.0,10.0,12.0,12.0,12.0,23.08,N,S,NaN,5,N,N,S,NaN,1.0,NaN,N,NaN,1.00,NaN,N,ZR02680018,50,Y,0,6948bd7d-d6b0-4953-b703-7cfde9e011a5,TOYOTA,SEQUOIA,2014.0,5TDDY5G10ES096867,5TDDY5G10ES096867,TOYOTA,SEQUOIA,2014,5985.0
50864,12.0,NaN,NaN,12.0,12.0,23.08,N,N,NaN,3,N,N,N,NaN,1.0,NaN,N,NaN,1.00,NaN,N,AE4727004H,35,N,0,44563f83-d4c0-42ee-94d1-81ac41b84c50,TOYT,SEQUIA,2014.0,5TDJW5G11ES094974,5TDJW5G11ES094974,TOYOTA,SEQUOIA,2014,5985.0
827,6.0,NaN,NaN,6.0,6.0,2.00,N,E,NaN,3,N,N,E,NaN,1.0,NaN,N,NaN,3.00,NaN,N,MSP6649005G,55,N,0,04ce29c7-5338-4719-a7c0-5d23a4bd6ef6,TOYT,TK,2013.0,5TDDY5G12DS079695,5TDDY5G12DS079695,TOYOTA,SEQUOIA,2013,5985.0
93594,NaN,NaN,NaN,12.0,10.0,2.00,N,S,NaN,0,N,N,S,NaN,1.0,NaN,Y,NaN,2.00,NaN,N,ADJ520000P,35,N,0,2bb62914-250f-4d03-8c81-12e4fdfa4790,TOYOTA,SEQUIOA,2013.0,5TDDY5G12DS090101,5TDDY5G12DS090101,TOYOTA,SEQUOIA,2013,5985.0
266978,12.0,NaN,NaN,12.0,12.0,2.00,N,W,NaN,3,N,N,W,NaN,1.0,NaN,N,NaN,1.00,NaN,N,AB60100009,30,N,0,8d0f57e0-58af-414a-8951-8b3fdbe6ff31,TOYOTA,STATION WAGON,2016.0,5TDJW5G12GS132523,5TDJW5G12GS132523,TOYOTA,SEQUOIA,2016,5985.0
258710,1.0,11.0,12.0,12.0,12.0,8.00,N,N,NaN,5,N,N,N,NaN,1.0,NaN,N,NaN,1.00,NaN,N,AC1958002P,50,Y,0,5cf848af-eed3-4a4b-a7a6-341b4be27103,TOYOTA,TK,2013.0,5TDJY5G13DS091230,5TDJY5G13DS091230,TOYOTA,SEQUOIA,2013,5985.0
389601,99.0,NaN,NaN,2.0,2.0,2.00,N,N,NaN,2,N,N,N,NaN,2.0,NaN,N,NaN,9.00,NaN,N,CP01400015,25,N,0,e9747930-70f2-4c85-9c83-6a1e4403a84c,TOYOTA,SEQUOIA,2016.0,5TDDY5G10GS147304,5TDDY5G10GS147304,TOYOTA,SEQUOIA,2016,5985.0
501351,9.0,10.0,NaN,10.0,10.0,23.08,N,W,NaN,3,N,N,W,NaN,1.0,NaN,N,NaN,1.00,NaN,N,ADI519003P,30,N,0,d32831f5-c845-4470-abad-cde0d5bf4573,TOYOTA,RAV4,2015.0,5TDBY5G10FS118939,5TDBY5G10FS118939,TOYOTA,SEQUOIA,2015,5985.0

Confirm that you have 532,370 vehicles in the dataset.

In [35]:
vehicles2.shape

(532370, 35)

## Add this vehicle information to your merged data

Now we'll have a dataframe that contains information on:

* The people themselves and their injuries
* The crash
* The vehicles

Every person came with a `VEHICLE_ID` column that is the vehicle they were in. You'll want to merge on that.

In [36]:
merged2 = pd.merge(merged, vehicles2, on='VEHICLE_ID')
merged2.head()

,ACC_DATE,ACC_TIME,AGENCY_CODE,AREA_CODE,COLLISION_TYPE_CODE,COUNTY_NO,C_M_ZONE_FLAG,DISTANCE,DISTANCE_DIR_FLAG,FEET_MILES_FLAG,FIX_OBJ_CODE,HARM_EVENT_CODE1,HARM_EVENT_CODE2,JUNCTION_CODE,LANE_CODE,LATITUDE,LIGHT_CODE,LOC_CODE,LOGMILE_DIR_FLAG,LOG_MILE,LONGITUDE,MAINROAD_NAME,MUNI_CODE,RD_COND_CODE,RD_DIV_CODE,REFERENCE_NO,REFERENCE_ROAD_NAME,REFERENCE_SUFFIX,REFERENCE_TYPE_CODE,REPORT_NO_x,REPORT_TYPE,ROUTE_TYPE_CODE,RTE_NO,RTE_SUFFIX,SIGNAL_FLAG,SURF_COND_CODE,WEATHER_CODE,AIRBAG_DEPLOYED,ALCOHOL_TESTTYPE_CODE,ALCOHOL_TEST_CODE,BAC_CODE,CDL_FLAG,CLASS,CONDITION_CODE,DATE_OF_BIRTH,DRUG_TESTRESULT_CODE,DRUG_TEST_CODE,EJECT_CODE,EMS_UNIT_LABEL,EQUIP_PROB_CODE,FAULT_FLAG,INJ_SEVER_CODE,LICENSE_STATE_CODE,MOVEMENT_CODE_x,OCC_SEAT_POS_CODE,PED_LOCATION_CODE,PED_OBEY_CODE,PED_TYPE_CODE,PED_VISIBLE_CODE,PERSON_ID,PERSON_TYPE,SAF_EQUIP_CODE,SEX_CODE,VEHICLE_ID,is_fatality,genders,condition,AREA_DAMAGED_CODE1,AREA_DAMAGED_CODE2,AREA_DAMAGED_CODE3,AREA_DAMAGED_CODE_IMP1,AREA_DAMAGED_CODE_MAIN,BODY_TYPE_CODE,COMMERCIAL_FLAG,CONTI_DIRECTION_CODE,CV_BODY_TYPE_CODE,DAMAGE_CODE,DRIVERLESS_FLAG,FIRE_FLAG,GOING_DIRECTION_CODE,GVW_CODE,HARM_EVENT_CODE,HAZMAT_SPILL_FLAG,HIT_AND_RUN_FLAG,HZM_NUM,MOVEMENT_CODE_y,NUM_AXLES,PARKED_FLAG,REPORT_NO_y,SPEED_LIMIT,TOWED_AWAY_FLAG,TOWED_VEHICLE_CONFIG_CODE,VEH_MAKE,VEH_MODEL,VEH_YEAR,VIN_NO,VIN,Make,Model,ModelYear,weight
0,2018-04-10 00:00:00,01:50:00,MSP,UNK,17,18.0,N,0.0,N,F,22.03,16.0,11.0,1.0,NaN,38.277230,4.0,NaN,N,2.09,-76.682876,NEWTOWNE NECK RD,0.0,1.0,1.0,166.0,ROSEBANK RD,NaN,CO,MSP6188002Q,Injury Crash,MD,243.0,NaN,N,2.0,6.01,4.0,2.0,3.0,NaN,N,C,2.0,1996-12-13 00:00:00,NaN,0.0,1.0,A,1.0,Y,3,MD,NaN,NaN,NaN,NaN,NaN,NaN,0212a82f-38a7-4a8a-969d-bce0920d3ab3,D,13.0,F,61d02432-7d40-401a-86ce-fea710234832,0,1.0,Dry,1.0,11.0,12.0,12.0,12.0,2.00,N,N,NaN,5,N,N,N,NaN,16.0,NaN,N,NaN,1.0,NaN,N,MSP6188002Q,40,Y,0,MITSUBISHI,MIRAGE,2017.0,ML32A4HJ0HH009937,ML32A4HJ0HH009937,MITSUBISHI,MIRAGE,2017,2045.0
1,2018-05-02 00:00:00,11:06:00,ELKTON,UNK,5,7.0,N,15.0,S,F,0.00,1.0,1.0,3.0,NaN,39.613747,1.0,NaN,N,19.41,-75.837454,N BRIDGE ST,52.0,1.0,3.0,362.0,LAUREL DR,NaN,MU,BK0227001M,Injury Crash,MD,213.0,NaN,N,2.0,6.01,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1967-11-19 00:00:00,NaN,NaN,1.0,NaN,1.0,NaN,3,NaN,NaN,3.0,NaN,NaN,NaN,NaN,006b94ad-a347-4356-a48b-9b4b0849ae7b,O,13.0,F,089ece89-1c91-4fc4-a2f9-3368a8649a96,0,1.0,Dry,6.0,11.0,12.0,6.0,6.0,23.08,N,W,NaN,5,N,N,N,NaN,1.0,NaN,N,NaN,3.0,NaN,N,BK0227001M,35,N,0,HONDA,CRV,2006.0,SHSRD78946U439857,SHSRD78946U439857,HONDA,CR-V,2006,3318.0
2,2018-05-02 00:00:00,11:06:00,ELKTON,UNK,5,7.0,N,15.0,S,F,0.00,1.0,1.0,3.0,NaN,39.613747,1.0,NaN,N,19.41,-75.837454,N BRIDGE ST,52.0,1.0,3.0,362.0,LAUREL DR,NaN,MU,BK0227001M,Injury Crash,MD,213.0,NaN,N,2.0,6.01,1.0,NaN,0.0,NaN,N,C,1.0,1954-08-18 00:00:00,NaN,0.0,1.0,B,1.0,N,3,MD,NaN,NaN,NaN,NaN,NaN,NaN,4fb7ba1d-4e1d-466c-a84c-de24d99ff7d0,D,13.0,M,089ece89-1c91-4fc4-a2f9-3368a8649a96,0,0.0,Dry,6.0,11.0,12.0,6.0,6.0,23.08,N,W,NaN,5,N,N,N,NaN,1.0,NaN,N,NaN,3.0,NaN,N,BK0227001M,35,N,0,HONDA,CRV,2006.0,SHSRD78946U439857,SHSRD78946U439857,HONDA,CR-V,2006,3318.0
3,2018-05-02 00:00:00,11:06:00,ELKTON,UNK,5,7.0,N,15.0,S,F,0.00,1.0,1.0,3.0,NaN,39.613747,1.0,NaN,N,19.41,-75.837454,N BRIDGE ST,52.0,1.0,3.0,362.0,LAUREL DR,NaN,MU,BK0227001M,Injury Crash,MD,213.0,NaN,N,2.0,6.01,5.0,NaN,0.0,NaN,N,B,99.0,1948-04-23 00:00:00,NaN,0.0,1.0,A,1.0,Y,3,MD,NaN,NaN,NaN,NaN,NaN,NaN,a6ad59e0-a578-4093-a6df-99a66c936821,D,13.0,M,3326638d-db2b-416e-974c-fc385d6552b9,0,0.0,Dry,11.0,12.0,NaN,12.0,12.0,23.08,N,N,NaN,4,N,N,N,NaN,1.0,NaN,N,NaN,1.0,NaN,N,BK0227001M,35,Y,0,DODGE,DURANGO,2015.0,1C4RDJDG1FC843317,1C4RDJDG1FC843317,DODGE,DURANGO,2015,4756.0
4,2018-05-02 00:00:00,12:45:00,MONTGOMERY,UNK,7,15.0,N,0.0,E,F,0.00,1.0,1.0,2.0,2.0,39.015649,1.0,55122,E,0.00,-77.042728,FOREST GLEN RD,0.0,0.0,4.0,97.0,GEORGIA AVE,NaN,MD,MCP2891005S,Property Damage Crash,CO,697.0,NaN,Y,2.0,6.01,1.0,NaN,0.0,NaN,N,C,1.0,1988-09-11 00:00:00,NaN,0.0,1.0,NaN,0.0,N,1,MD,NaN,NaN,NaN,NaN,NaN,NaN,76e97f6c-9a05-462a-8a7d-833753dd48f7,D,13.0,M,0fbcd761-3428-4cad-a121-0d3696262b59,0,0.0,Dry,7.0,NaN,NaN,7.0,7.0,2.00,N,S,NaN,3,N,N,W,NaN,1.0,NaN,N,NaN,12.0,NaN,N,MCP2891005S,35,N,0,NISSAN,SENTRA,2013.0,3N1AB7AP1DL615347,3N1AB7AP1DL615347,NISSAN,SENTRA,2013,2902.0

Confirm you have 99 columns and 616,212 rows. **That is a lot of possible features!**

In [37]:
merged2.shape

(616212, 101)

## Another regression, because we can't get enough

Build another `train_df` and run another regression about **how car weight impacts the chance of fatalities**. You'll want to confirm that your dataset has 616,212 and 2 columns.

In [38]:
train_df = merged2.copy()
train_df = train_df[['is_fatality', 'weight']]

In [39]:
X = train_df.drop(columns=['is_fatality'])
y = train_df.is_fatality

In [40]:
clf = LogisticRegression(C=1e9, solver='lbfgs')
clf.fit(X, y)

LogisticRegression(C=1000000000.0, class_weight=None, dual=False,
                   fit_intercept=True, intercept_scaling=1, l1_ratio=None,
                   max_iter=100, multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [41]:
feature_names = X.columns
coefficients = clf.coef_[0]

pd.DataFrame({
    'feature': feature_names,
    'coefficient (log odds ratio)': coefficients,
    'odds ratio': np.exp(coefficients)
}).sort_values(by='odds ratio', ascending=False)

  feature  coefficient (log odds ratio)  odds ratio
0  weight                     -0.000147    0.999853

**Can you translate that into plain English?** Remember weight is in **pounds**.

In [42]:
# Every pound heavier your car is translates to a 1% decrease in fatalities

I feel like pounds isn't the best measure for something like this. Remember how we had to adjust percentages with AP and life expecntancy, and then change around the way we said things? It sounded like this:

> Every 10% increase in unemployment translates to a year and a half loss of life expectancy

Instead of every single pound, maybe we could do every... some other number of pounds? One hundred? One thousand?

**Run another regression with weight in thousands of pounds.** Get another odds ratio. Give me another sentence English.

In [43]:
train_df['weight'] = train_df.weight/1000

In [44]:
train_df = merged2.copy()
train_df = train_df[['is_fatality', 'weight']]
train_df['weight'] = train_df.weight/1000

In [45]:
X = train_df.drop(columns=['is_fatality'])
y = train_df.is_fatality

In [46]:
clf = LogisticRegression(C=1e9, solver='lbfgs')
clf.fit(X, y)

LogisticRegression(C=1000000000.0, class_weight=None, dual=False,
                   fit_intercept=True, intercept_scaling=1, l1_ratio=None,
                   max_iter=100, multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [47]:
feature_names = X.columns
coefficients = clf.coef_[0]

pd.DataFrame({
    'feature': feature_names,
    'coefficient (log odds ratio)': coefficients,
    'odds ratio': np.exp(coefficients)
}).sort_values(by='odds ratio', ascending=False)

  feature  coefficient (log odds ratio)  odds ratio
0  weight                     -0.146881    0.863397

In [48]:
# Every thousand pounds heavier your car is increase translates to a 15% decrease in fatalities

# Two-car accidents, struck and striker

Here's the thing, though: **it isn't just the weight of your car.** It's the weight of both cars! If I'm in a big car and I have a wreck with a smaller car, it's the smaller car that's in trouble.

To get that value, we need to do some **feature engineering**, some calculating of *new* variables from our *existing* variables.

We need to jump through some hoops to do that.

##  Two-car accidents

First we're going to count how many vehicles were in each accident. Since we're looking to compare the weight of two cars hitting each other, **we're only going to want crashes with only two cars.**

In [49]:
counted = vehicles.REPORT_NO.value_counts()
counted.head(10)

MDTA1229000H    69
CB53480003      35
MSP67460095     18
CE4636002C      17
MSP6063005N     17
AS0286000B      17
MSP6063006C     15
MSP637800B1     15
DA3276000V      14
CC0237003W      14
Name: REPORT_NO, dtype: int64

By using `.value_counts` I can see how many cars were in each crash, and now I'm going to filter to get a list of all of the ones with two vehicles.

In [50]:
two_car_report_nos = counted[counted == 2].index
two_car_report_nos

Index(['ADJ2990014', 'MTA03430005', 'ADJ216000J', 'CBPD0091001B',
       'MSP12810012', 'MDTA1553000Q', 'AE4747000K', 'DA3805001K',
       'MSP6593006D', 'DA3375001C',
       ...
       'MSP546600JB', 'BX5185000D', 'EJ78560032', 'MSP6171009J', 'ADD721006J',
       'ADJ465002W', 'AE57320015', 'ZR0279001D', 'ZL0846000C', 'AE5917000T'],
      dtype='object', length=253146)

And now we'll filter my vehicles so we only have those that were in two-vehicle crashes.

In [51]:
vehicles = vehicles[vehicles.REPORT_NO.isin(two_car_report_nos)]

### Struck and striker

To do the math correctly, we need both the risk of someone dying in the smaller car _and_ the risk of someone dying in the bigger car. To do this we need to separate our cars into two groups:

* The 'struck' vehicle: did the person die inside?
* The 'striker' vehicle: how much heavier was it than the struck car?

But we don't know which car was which, so we have to try out both versions - pretending car A was the striker, then pretending car B was the striker. It's hard to explain, but you can read `Pounds That Kill - The External Costs of Vehicle Weight.pdf` for more details on how it works.

In [52]:
cars_1 = vehicles.drop_duplicates(subset='REPORT_NO', keep='first')
cars_2 = vehicles.drop_duplicates(subset='REPORT_NO', keep='last')

In [53]:
cars_merged_1 = cars_1.merge(cars_2, on='REPORT_NO', suffixes=['_striker', '_struck'])
cars_merged_2 = cars_2.merge(cars_1, on='REPORT_NO', suffixes=['_striker', '_struck'])
vehicles_complete = pd.concat([cars_merged_1, cars_merged_2])
vehicles_complete.head()

,AREA_DAMAGED_CODE1_striker,AREA_DAMAGED_CODE2_striker,AREA_DAMAGED_CODE3_striker,AREA_DAMAGED_CODE_IMP1_striker,AREA_DAMAGED_CODE_MAIN_striker,BODY_TYPE_CODE_striker,COMMERCIAL_FLAG_striker,CONTI_DIRECTION_CODE_striker,CV_BODY_TYPE_CODE_striker,DAMAGE_CODE_striker,DRIVERLESS_FLAG_striker,FIRE_FLAG_striker,GOING_DIRECTION_CODE_striker,GVW_CODE_striker,HARM_EVENT_CODE_striker,HAZMAT_SPILL_FLAG_striker,HIT_AND_RUN_FLAG_striker,HZM_NUM_striker,MOVEMENT_CODE_striker,NUM_AXLES_striker,PARKED_FLAG_striker,REPORT_NO,SPEED_LIMIT_striker,TOWED_AWAY_FLAG_striker,TOWED_VEHICLE_CONFIG_CODE_striker,VEHICLE_ID_striker,VEH_MAKE_striker,VEH_MODEL_striker,VEH_YEAR_striker,VIN_NO_striker,AREA_DAMAGED_CODE1_struck,AREA_DAMAGED_CODE2_struck,AREA_DAMAGED_CODE3_struck,AREA_DAMAGED_CODE_IMP1_struck,AREA_DAMAGED_CODE_MAIN_struck,BODY_TYPE_CODE_struck,COMMERCIAL_FLAG_struck,CONTI_DIRECTION_CODE_struck,CV_BODY_TYPE_CODE_struck,DAMAGE_CODE_struck,DRIVERLESS_FLAG_struck,FIRE_FLAG_struck,GOING_DIRECTION_CODE_struck,GVW_CODE_struck,HARM_EVENT_CODE_struck,HAZMAT_SPILL_FLAG_struck,HIT_AND_RUN_FLAG_struck,HZM_NUM_struck,MOVEMENT_CODE_struck,NUM_AXLES_struck,PARKED_FLAG_struck,SPEED_LIMIT_struck,TOWED_AWAY_FLAG_struck,TOWED_VEHICLE_CONFIG_CODE_struck,VEHICLE_ID_struck,VEH_MAKE_struck,VEH_MODEL_struck,VEH_YEAR_struck,VIN_NO_struck
0,8.0,NaN,NaN,8.0,8.0,2.0,N,W,NaN,2,N,NaN,W,NaN,1.0,NaN,N,NaN,8.0,NaN,N,ADJ4590035,5,N,0,00050484-d08f-4b6e-bc7e-9ec270e94660,HONDA,CIVIC,2015.0,2HGFG4A59FH702545,99.0,NaN,NaN,99.0,99.0,2.00,N,W,NaN,99,N,N,W,NaN,1.0,NaN,Y,NaN,1.0,NaN,N,5,N,0,3ebfe7fc-4832-414d-a5e8-391b65a2f280,HONDA,ACCORD,2013.0,1HGCT2B81DA005695
1,12.0,NaN,NaN,12.0,12.0,2.0,N,N,NaN,4,N,NaN,N,NaN,0.0,NaN,N,NaN,1.0,NaN,N,ADJ849000Z,10,N,0,00057af4-d848-4cee-b854-707f57581f4e,HONDA,ACCORD,2003.0,1HGCM66313A037175,12.0,NaN,NaN,12.0,12.0,2.00,N,NaN,NaN,3,Y,NaN,NaN,NaN,1.0,NaN,N,NaN,10.0,NaN,Y,0,N,0,4cf496cc-f537-447e-bb8e-3ef48c8c3ddf,HONDA,TK,2010.0,5J6RE3H73AL008454
2,1.0,11.0,12.0,12.0,12.0,2.0,N,S,NaN,4,N,N,S,NaN,1.0,NaN,N,NaN,12.0,NaN,N,AE5207008Z,30,Y,0,00089d4a-7038-4693-9e02-b402676631af,FORD,4D,2016.0,1FADP3K28GL258987,11.0,12.0,NaN,12.0,12.0,23.08,N,N,NaN,4,N,N,N,NaN,1.0,NaN,N,NaN,1.0,NaN,N,30,Y,0,1e69b284-719f-429b-baae-6ae4976a546b,BUICK,TK,2002.0,3G5DB03E52S528316
3,6.0,NaN,NaN,6.0,6.0,2.0,N,S,NaN,2,N,N,S,NaN,1.0,NaN,N,NaN,3.0,NaN,N,MCP27070015,25,N,0,000f45d8-bc0e-4f9c-820a-474212e669cd,ACUR,TSX,2008.0,JH4CL96848C021626,12.0,NaN,NaN,12.0,12.0,2.00,N,S,NaN,2,N,N,S,NaN,1.0,NaN,N,NaN,3.0,NaN,N,25,N,0,6e89f5d9-b4c5-4571-a511-6259f408bde9,ACUR,TL,2010.0,19UUA8F56AA011310
4,2.0,NaN,NaN,2.0,2.0,2.0,N,S,NaN,99,N,N,S,NaN,1.0,NaN,Y,NaN,1.0,NaN,N,ADJ859000Y,15,N,0,0010076b-0a45-45f3-8796-f387b39cd85d,HONDA,CIVIC,2009.0,2HGFA16689H357624,10.0,NaN,NaN,10.0,10.0,2.00,N,NaN,NaN,3,Y,N,NaN,NaN,1.0,NaN,N,NaN,10.0,NaN,Y,15,N,0,b14273cb-b3e5-42c7-af59-df069e8c2f0f,HONDA,CIVIC,2011.0,2HGFG1B87BH517469

## Put people in their cars

Which car was each person in? We'll assign that now.

In [54]:
merged = people.merge(vehicles_complete, left_on='VEHICLE_ID', right_on='VEHICLE_ID_struck')
merged.head(3)

,AIRBAG_DEPLOYED,ALCOHOL_TESTTYPE_CODE,ALCOHOL_TEST_CODE,BAC_CODE,CDL_FLAG,CLASS,CONDITION_CODE,DATE_OF_BIRTH,DRUG_TESTRESULT_CODE,DRUG_TEST_CODE,EJECT_CODE,EMS_UNIT_LABEL,EQUIP_PROB_CODE,FAULT_FLAG,INJ_SEVER_CODE,LICENSE_STATE_CODE,MOVEMENT_CODE,OCC_SEAT_POS_CODE,PED_LOCATION_CODE,PED_OBEY_CODE,PED_TYPE_CODE,PED_VISIBLE_CODE,PERSON_ID,PERSON_TYPE,REPORT_NO_x,SAF_EQUIP_CODE,SEX_CODE,VEHICLE_ID,is_fatality,genders,AREA_DAMAGED_CODE1_striker,AREA_DAMAGED_CODE2_striker,AREA_DAMAGED_CODE3_striker,AREA_DAMAGED_CODE_IMP1_striker,AREA_DAMAGED_CODE_MAIN_striker,BODY_TYPE_CODE_striker,COMMERCIAL_FLAG_striker,CONTI_DIRECTION_CODE_striker,CV_BODY_TYPE_CODE_striker,DAMAGE_CODE_striker,DRIVERLESS_FLAG_striker,FIRE_FLAG_striker,GOING_DIRECTION_CODE_striker,GVW_CODE_striker,HARM_EVENT_CODE_striker,HAZMAT_SPILL_FLAG_striker,HIT_AND_RUN_FLAG_striker,HZM_NUM_striker,MOVEMENT_CODE_striker,NUM_AXLES_striker,PARKED_FLAG_striker,REPORT_NO_y,SPEED_LIMIT_striker,TOWED_AWAY_FLAG_striker,TOWED_VEHICLE_CONFIG_CODE_striker,VEHICLE_ID_striker,VEH_MAKE_striker,VEH_MODEL_striker,VEH_YEAR_striker,VIN_NO_striker,AREA_DAMAGED_CODE1_struck,AREA_DAMAGED_CODE2_struck,AREA_DAMAGED_CODE3_struck,AREA_DAMAGED_CODE_IMP1_struck,AREA_DAMAGED_CODE_MAIN_struck,BODY_TYPE_CODE_struck,COMMERCIAL_FLAG_struck,CONTI_DIRECTION_CODE_struck,CV_BODY_TYPE_CODE_struck,DAMAGE_CODE_struck,DRIVERLESS_FLAG_struck,FIRE_FLAG_struck,GOING_DIRECTION_CODE_struck,GVW_CODE_struck,HARM_EVENT_CODE_struck,HAZMAT_SPILL_FLAG_struck,HIT_AND_RUN_FLAG_struck,HZM_NUM_struck,MOVEMENT_CODE_struck,NUM_AXLES_struck,PARKED_FLAG_struck,SPEED_LIMIT_struck,TOWED_AWAY_FLAG_struck,TOWED_VEHICLE_CONFIG_CODE_struck,VEHICLE_ID_struck,VEH_MAKE_struck,VEH_MODEL_struck,VEH_YEAR_struck,VIN_NO_struck
0,1.0,NaN,0.0,NaN,N,C,0.0,1952-04-20 00:00:00,NaN,0.0,1.0,NaN,1.0,N,1,PA,NaN,NaN,NaN,NaN,NaN,NaN,48dd00ee-e033-47e7-ad1e-0b734020301b,D,AB4284000S,13.0,F,eb6aadb8-dacb-4744-a1a7-ab812c96f27f,0,1.0,12.0,NaN,NaN,12.0,12.0,2.0,N,N,NaN,2,N,N,N,NaN,1.0,NaN,Y,NaN,2.0,NaN,N,AB4284000S,25,N,0,e95fc5fb-a269-4cce-9e09-643cd6a5bde7,TOYT,4S,2007.0,JTNBB46K073032308,6.0,NaN,NaN,6.0,6.0,2.0,N,N,NaN,2,N,N,N,NaN,1.0,NaN,N,NaN,6.0,NaN,N,25,N,0,eb6aadb8-dacb-4744-a1a7-ab812c96f27f,HYND,SONATA,2015.0,5NPE34AB7FH113136
1,1.0,NaN,0.0,NaN,N,NaN,0.0,1985-05-28 00:00:00,NaN,0.0,0.0,NaN,0.0,N,1,MD,NaN,NaN,NaN,NaN,NaN,NaN,166296bd-ffd3-4c16-aa74-4f4bf4139d8d,D,AB4313000X,13.0,F,b463eb20-2f01-4200-9d6f-b18888ce2593,0,1.0,3.0,NaN,NaN,3.0,3.0,2.0,N,E,NaN,2,N,NaN,E,NaN,1.0,NaN,Y,NaN,2.0,NaN,N,AB4313000X,25,N,0,3c8629d0-d524-47c1-bfbc-b18e07f3087e,LEXU,TK,2004.0,2T2HA31U24C031048,7.0,NaN,NaN,7.0,7.0,2.0,N,S,NaN,2,N,N,S,NaN,1.0,NaN,N,NaN,6.0,NaN,N,25,N,0,b463eb20-2f01-4200-9d6f-b18888ce2593,CHEVY,TK,2007.0,2CNDL13F576252855
2,1.0,NaN,0.0,NaN,N,C,0.0,1960-10-04 00:00:00,NaN,0.0,0.0,NaN,0.0,Y,1,MD,NaN,NaN,NaN,NaN,NaN,NaN,f3b2743f-fbc3-4345-9419-56a0ca29102c,D,AB4313000X,13.0,F,3c8629d0-d524-47c1-bfbc-b18e07f3087e,0,1.0,7.0,NaN,NaN,7.0,7.0,2.0,N,S,NaN,2,N,N,S,NaN,1.0,NaN,N,NaN,6.0,NaN,N,AB4313000X,25,N,0,b463eb20-2f01-4200-9d6f-b18888ce2593,CHEVY,TK,2007.0,2CNDL13F576252855,3.0,NaN,NaN,3.0,3.0,2.0,N,E,NaN,2,N,NaN,E,NaN,1.0,NaN,Y,NaN,2.0,NaN,N,25,N,0,3c8629d0-d524-47c1-bfbc-b18e07f3087e,LEXU,TK,2004.0,2T2HA31U24C031048

# Add the crash details

You did this already! I'm going to do it for you. We're merging on `REPORT_NO_x` because there are so many `REPORT_NO` columns duplicated across our files that pandas started giving them weird names.

In [55]:
merged = merged.merge(combined, left_on='REPORT_NO_x', right_on='REPORT_NO')
merged.head(3)

,AIRBAG_DEPLOYED,ALCOHOL_TESTTYPE_CODE,ALCOHOL_TEST_CODE,BAC_CODE,CDL_FLAG,CLASS,CONDITION_CODE,DATE_OF_BIRTH,DRUG_TESTRESULT_CODE,DRUG_TEST_CODE,EJECT_CODE,EMS_UNIT_LABEL,EQUIP_PROB_CODE,FAULT_FLAG,INJ_SEVER_CODE,LICENSE_STATE_CODE,MOVEMENT_CODE,OCC_SEAT_POS_CODE,PED_LOCATION_CODE,PED_OBEY_CODE,PED_TYPE_CODE,PED_VISIBLE_CODE,PERSON_ID,PERSON_TYPE,REPORT_NO_x,SAF_EQUIP_CODE,SEX_CODE,VEHICLE_ID,is_fatality,genders,AREA_DAMAGED_CODE1_striker,AREA_DAMAGED_CODE2_striker,AREA_DAMAGED_CODE3_striker,AREA_DAMAGED_CODE_IMP1_striker,AREA_DAMAGED_CODE_MAIN_striker,BODY_TYPE_CODE_striker,COMMERCIAL_FLAG_striker,CONTI_DIRECTION_CODE_striker,CV_BODY_TYPE_CODE_striker,DAMAGE_CODE_striker,DRIVERLESS_FLAG_striker,FIRE_FLAG_striker,GOING_DIRECTION_CODE_striker,GVW_CODE_striker,HARM_EVENT_CODE_striker,HAZMAT_SPILL_FLAG_striker,HIT_AND_RUN_FLAG_striker,HZM_NUM_striker,MOVEMENT_CODE_striker,NUM_AXLES_striker,PARKED_FLAG_striker,REPORT_NO_y,SPEED_LIMIT_striker,TOWED_AWAY_FLAG_striker,TOWED_VEHICLE_CONFIG_CODE_striker,VEHICLE_ID_striker,VEH_MAKE_striker,VEH_MODEL_striker,VEH_YEAR_striker,VIN_NO_striker,AREA_DAMAGED_CODE1_struck,AREA_DAMAGED_CODE2_struck,AREA_DAMAGED_CODE3_struck,AREA_DAMAGED_CODE_IMP1_struck,AREA_DAMAGED_CODE_MAIN_struck,BODY_TYPE_CODE_struck,COMMERCIAL_FLAG_struck,CONTI_DIRECTION_CODE_struck,CV_BODY_TYPE_CODE_struck,DAMAGE_CODE_struck,DRIVERLESS_FLAG_struck,FIRE_FLAG_struck,GOING_DIRECTION_CODE_struck,GVW_CODE_struck,HARM_EVENT_CODE_struck,HAZMAT_SPILL_FLAG_struck,HIT_AND_RUN_FLAG_struck,HZM_NUM_struck,MOVEMENT_CODE_struck,NUM_AXLES_struck,PARKED_FLAG_struck,SPEED_LIMIT_struck,TOWED_AWAY_FLAG_struck,TOWED_VEHICLE_CONFIG_CODE_struck,VEHICLE_ID_struck,VEH_MAKE_struck,VEH_MODEL_struck,VEH_YEAR_struck,VIN_NO_struck,ACC_DATE,ACC_TIME,AGENCY_CODE,AREA_CODE,COLLISION_TYPE_CODE,COUNTY_NO,C_M_ZONE_FLAG,DISTANCE,DISTANCE_DIR_FLAG,FEET_MILES_FLAG,FIX_OBJ_CODE,HARM_EVENT_CODE1,HARM_EVENT_CODE2,JUNCTION_CODE,LANE_CODE,LATITUDE,LIGHT_CODE,LOC_CODE,LOGMILE_DIR_FLAG,LOG_MILE,LONGITUDE,MAINROAD_NAME,MUNI_CODE,RD_COND_CODE,RD_DIV_CODE,REFERENCE_NO,REFERENCE_ROAD_NAME,REFERENCE_SUFFIX,REFERENCE_TYPE_CODE,REPORT_NO,REPORT_TYPE,ROUTE_TYPE_CODE,RTE_NO,RTE_SUFFIX,SIGNAL_FLAG,SURF_COND_CODE,WEATHER_CODE
0,1.0,NaN,0.0,NaN,N,C,0.0,1952-04-20 00:00:00,NaN,0.0,1.0,NaN,1.0,N,1,PA,NaN,NaN,NaN,NaN,NaN,NaN,48dd00ee-e033-47e7-ad1e-0b734020301b,D,AB4284000S,13.0,F,eb6aadb8-dacb-4744-a1a7-ab812c96f27f,0,1.0,12.0,NaN,NaN,12.0,12.0,2.0,N,N,NaN,2,N,N,N,NaN,1.0,NaN,Y,NaN,2.0,NaN,N,AB4284000S,25,N,0,e95fc5fb-a269-4cce-9e09-643cd6a5bde7,TOYT,4S,2007.0,JTNBB46K073032308,6.0,NaN,NaN,6.0,6.0,2.0,N,N,NaN,2,N,N,N,NaN,1.0,NaN,N,NaN,6.0,NaN,N,25,N,0,eb6aadb8-dacb-4744-a1a7-ab812c96f27f,HYND,SONATA,2015.0,5NPE34AB7FH113136,2018-05-25 00:00:00,10:58:00,ANNAPOLIS,UNK,3,2.0,N,20.0,S,F,0.0,1.0,0.0,3.0,1.0,38.950029,1.0,NaN,S,0.00,-76.492578,HILLSMERE DR,3.0,1.0,5.01,2930.0,BAY RIDGE RD,NaN,CO,AB4284000S,Property Damage Crash,CO,2885.0,NaN,Y,2.0,6.01
1,0.0,NaN,0.0,NaN,N,C,1.0,1994-12-13 00:00:00,NaN,0.0,1.0,NaN,1.0,Y,1,MD,NaN,NaN,NaN,NaN,NaN,NaN,974e41b6-480e-431f-9585-4b87f4c29b19,D,AB4284000S,13.0,F,e95fc5fb-a269-4cce-9e09-643cd6a5bde7,0,1.0,6.0,NaN,NaN,6.0,6.0,2.0,N,N,NaN,2,N,N,N,NaN,1.0,NaN,N,NaN,6.0,NaN,N,AB4284000S,25,N,0,eb6aadb8-dacb-4744-a1a7-ab812c96f27f,HYND,SONATA,2015.0,5NPE34AB7FH113136,12.0,NaN,NaN,12.0,12.0,2.0,N,N,NaN,2,N,N,N,NaN,1.0,NaN,Y,NaN,2.0,NaN,N,25,N,0,e95fc5fb-a269-4cce-9e09-643cd6a5bde7,TOYT,4S,2007.0,JTNBB46K073032308,2018-05-25 00:00:00,10:58:00,ANNAPOLIS,UNK,3,2.0,N,20.0,S,F,0.0,1.0,0.0,3.0,1.0,38.950029,1.0,NaN,S,0.00,-76.492578,HILLSMERE DR,3.0,1.0,5.01,2930.0,BAY RIDGE RD,NaN,CO,AB4284000S,Property Damage Crash,CO,2885.0,NaN,Y,2.0,6.01
2,1.0,NaN,0.0,NaN,N,NaN,0.0,1985-05-28 00:00:00,NaN,0.0,0.0,NaN,0.0,N,1,MD,NaN,NaN,NaN,NaN,NaN,NaN,166296bd-ffd3-4c16-aa74-4f4bf4139d8d,D,AB4313000X,13.0,F,b463eb20-2f01-4200-9d6f-b18888ce2593,0,1.0,3.0,NaN,NaN,3.0,3.0,2.0,N,E,NaN,2,N,NaN,E,NaN,1.0,NaN,Y,NaN,2.0,NaN,N,AB4313000X,25,N,0,3c8629d0-d524-47c1-bfbc-b18e07f3087e,LEXU,TK,2004.0,2T2HA31U24C031048,7.0,NaN,NaN,7.0,7.0,2.0,N,S,NaN,2,N,N,S,NaN,1.0,NaN,N,NaN,6.0,NaN,N,25,N,0,b463eb20-2f01-4200-9d6f-b18888ce2593,CHEVY,TK,2007.0,2CNDL13F576252855,2018-04-19 00:00:00,15:50:00,ANNAPOLIS,UNK,3,2.0,N,0.0,S,F,0.0,1.0,0.0,0.0,1.0,38.976882,1.0,NaN,N,0.01,-76.486787,COMPROMISE ST,3.0,0.0,1.00,960.0,DUKE OF GLOUCHESTER ST,NaN,MU,AB4313000X,Property Damage Crash,MU,740.0,NaN,N,0.0,7.01

## Filter

We already filtered out vehicles by weight, so we don't have to do that again.

# Calculated features

I'm sure you forgot what all the features are, so we'll bring back whether there was a fatality or not

## Feature: Accident was fatal

In [56]:
merged['had_fatality'] = (merged.INJ_SEVER_CODE == 5).astype(int)
merged.had_fatality.value_counts()

0    601107
1       598
Name: had_fatality, dtype: int64

## Feature: Weight difference

**Remove everything missing weights for strikers or struck vehicles.** You might need to `merged.columns` to remind yourself what the column names are.

In [57]:
merged.columns

Index(['AIRBAG_DEPLOYED', 'ALCOHOL_TESTTYPE_CODE', 'ALCOHOL_TEST_CODE',
       'BAC_CODE', 'CDL_FLAG', 'CLASS', 'CONDITION_CODE', 'DATE_OF_BIRTH',
       'DRUG_TESTRESULT_CODE', 'DRUG_TEST_CODE',
       ...
       'REFERENCE_TYPE_CODE', 'REPORT_NO', 'REPORT_TYPE', 'ROUTE_TYPE_CODE',
       'RTE_NO', 'RTE_SUFFIX', 'SIGNAL_FLAG', 'SURF_COND_CODE', 'WEATHER_CODE',
       'had_fatality'],
      dtype='object', length=127)

In [59]:
# merged = merged.dropna(subset=['weight_striker', 'weight_struck'])
# merged.head()

Confirm your dataset has 334,396 rows.

Create a new feature called `weight_diff` about how much heavier the striking car was compared to the struck car. **Make sure you've done the math correctly!**

### Feature adjustment

Make all of your weight columns in **thousands of pounds** instead of just in pounds. It'll help you interpret your results much better.

# Another regression!!!

**What is the impact of weight difference on fatality rate?** Create your `train_df`, drop missing values, run your regression, analyze your odds ratios.

Please translate your odds ratio into plain English.

## Adding in more features

How about speed limit? That's important, right? We can add the speed limit of the striking vehicle with `SPEED_LIMIT_striker`.

Can you translate the speed limit odds ratio into plain English?

### Feature engineering: Speed limits

Honestly, that's a pretty bad way to go about things. What's more fun is if we **translate speed limits into bins.**

First, we'll use `pd.cut` to assign each speed limit a category.

In [ ]:
speed_bins = [-np.inf, 10, 20, 30, 40, 50, np.inf]
merged['speed_bin'] = pd.cut(merged.SPEED_LIMIT_struck, bins=speed_bins)
merged[['SPEED_LIMIT_striker', 'speed_bin']].head(10)

Then we'll one-hot encode around 20-30mph speed limits.

In [ ]:
speed_dummies = pd.get_dummies(merged.speed_bin, 
                               prefix='speed').drop('speed_(20.0, 30.0]', axis=1)
speed_dummies.head()

## Running a regression

I like this layout for creating `train_df`, it allows us to easily add dummies and do a little replacing/encoding when we're building binary features like for sex.

> If the below gives you an error, it's because `SEX_CODE` is already a number. In that case, just remove `.replace({'M': 1, 'F': 0, 'U': np.nan })`.

In [ ]:
# Start with our normal features
train_df = pd.DataFrame({
    'weight_diff': merged.weight_diff,
    'sex': merged.SEX_CODE,#.replace({'M': 1, 'F': 0, 'U': np.nan }),
    'had_fatality': merged.had_fatality,
})
# Add the one-hot encoded features
train_df = train_df.join(speed_dummies)
train_df = train_df.join(surf_dummies)
# Drop missing values
train_df = train_df.dropna()
train_df.head()

Describe the impact of the different variables in simple language. What has the largest impact?

## Now you pick the features

Up above you have examples of:

* Creating features from numbers (speed limits)
* Creating features from 0/1 (sex)
* Creating features from binning numbers that are one-hot encoded (speed limit bins - `speed_bins`)
* Creating features from categories that are one-hot encoded (surface - `surf_dummies`

What else do you think matters? Try to plug in more features and see if you can get anything interesting.

> * **Hot tip:** The funniest/most interesting thing feature you can add is also the dumbest. Ask me about it in #algorithms if you end up getting down here.